### ISSUE TITLE
ArgGroup fails to initialize with subcommands as method

### ISSUE THREAD

**Issue by usmansaleem** [remkop/picocli#974] opened 2020-03-11 00:26 UTC
**Version:** 4.2.0

## Problem
If ArgGroup are used with subcommand as method, at run time PicoCLI fails to initialize.
## Steps to reproduce
~~~
package com.picoclitest;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "App", mixinStandardHelpOptions = true, version = "1.0")
public class App implements Runnable {

    static class Exclusive {
        @Option(names = "-a", description = "a", required=true)
        String a;
        @Option(names = "-b", description = "b", required=true)
        String b;
    }
    @Command(name = "generate", description = "Generate")
    void generate(@Option(names = "-x", description = "x", required=true)
                          int x,
                  @Option(names = "-y", description = "y", required=true)
                          int y,
                  @CommandLine.ArgGroup Exclusive e) {
        System.out.printf("x=%s, y=%s", x, y);
        if (e == null) {
            System.out.println("-a and -b not specified");
        } else {
            System.out.printf("%s, %s\n", e.a, e.b);
        }
    }


    @Override
    public void run() {
        CommandLine.usage(this, System.out);
    }

    public static void main(String[] args) {
        new CommandLine(new App()).execute(args);
    }
}
~~~

* Running it cause following exception:
~~~
./picocli_method_subcommand generate -x=1 -y=1
picocli.CommandLine$PicocliException: Could not get value for field java.lang.String com.picoclitest.App$Exclusive.a
	at picocli.CommandLine$Model$FieldBinding.get(CommandLine.java:10137)
	at picocli.CommandLine$Model$ArgSpec.getValue(CommandLine.java:7628)
	at picocli.CommandLine$Model$CommandSpec.argValues(CommandLine.java:5904)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1797)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at com.picoclitest.App.main(App.java:40)
Caused by: java.lang.NullPointerException
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at picocli.CommandLine$Model$FieldBinding.get(CommandLine.java:10134)
	... 10 more
~~~

**Comment by remkop** [comment] 2020-03-11 02:45
Thank you for raising this! I’ll take a look when I get to my PC.

**Comment by remkop** [comment] 2020-03-11 04:05
@usmansaleem Thanks again for raising this! I’ve had a chance to look at it (thanks for the steps to reproduce, that helped a lot), and I found the cause. Basically, picocli version 4.2.0 is missing some logic that is necessary to support ArgGroups in  `@Command`-annotated methods. I intend to fix this for the next release.

**Comment by remkop** [comment] 2020-03-11 04:10
I believe the problem is limited to `@Command`-annotated methods, so as a workaround, you should be able to use a `Runnable` or `Callable` class to define subcommands that have `ArgGroups`.

**Comment by usmansaleem** [comment] 2020-03-11 04:29
@remkop Yes, the class based `@Command` and ArgGroups works without any problem :). I was able to use the workaround.

**Comment by remkop** [comment] 2020-03-17 10:31
@usmansaleem I pushed a fix to master.
Thank you again for reporting this!

If you want to verify, do this:

```
git clone https://github.com/remkop/picocli.git
cd picocli
gradlew publishToMavenLocal
```

That should publish `picocli-4.2.1-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.1-SNAPSHOT` dependency.

**Closed by remkop** 2020-03-17 10:31 UTC
Labels: bug, enhancement
