### ISSUE TITLE
Interactive CLI

### ISSUE THREAD

**Issue by adibrastegarnia** [remkop/picocli#380] opened 2018-05-18 02:42 UTC
Hello, 

I would like to build an interactive command line interface (like a shell) in order to avoid executing the code everytime for separate commands. How can I do that using picocli? 

Thanks

**Comment by remkop** [comment] 2018-05-18 04:59
Please take a look at the discussion on #242 and this pull request with work in progress: #293.

I have not been able to give this topic much thought yet. Any contributions are welcome!

**Comment by adibrastegarnia** [comment] 2018-05-18 13:28
Thanks. I will think about it.

**Comment by remkop** [comment] 2018-05-18 13:39
Basically, the only thing missing is some logic that reads lines from the console, and parses this line into tokens. After that, you simply invoke `CommandLine.parse` with the array of tokens. 

The pull request has work in progress to read from the console and tokenize. You can try this.  Feedback would be great!

**Comment by adibrastegarnia** [comment] 2018-05-18 14:15
Actually, I wrote a piece of code that do something similar to what you
explained:

Scanner scanner=new Scanner(System.in);
while (true) {
    System.out.print("\033[31;1mshell>> \033[0m");
    String cmd = scanner.nextLine();
    if(cmd.equals("quit")){
        break;
    }

    String[] arguments = cmd.split(" ");


    if(arguments[0].equals("topo"))
    {
        CommandLine.run(new TopoCommand(),
System.err,Arrays.copyOfRange(arguments, 1, arguments.length));
    }


}

In the code above, I just check the name of command to call an
appropriate command. By doing this, I can add new commands easily and
then update the code above

to support new commands.


What do you think?

**Comment by remkop** [comment] 2018-05-18 14:25
Right, that’s pretty much the idea. 
The sophisticated tokenizer comes into play when you want your app to be able to handle input like 

```
cmd -option=“abc def”
```

**Comment by adibrastegarnia** [comment] 2018-05-18 15:09
Thanks for the information.

**Comment by remkop** [comment] 2018-06-06 09:13
Would you mind if we close this as a duplicate of #242 ?

**Comment by adibrastegarnia** [comment] 2018-06-06 17:04
No. Please close it. Thanks for your help.

**Closed** 2018-06-06 23:14 UTC
Labels: duplicate
