### ISSUE TITLE
Picocli codegen fails on module-info.java

### ISSUE THREAD

**Issue by bdemers** [remkop/picocli#994] opened 2020-04-16 20:28 UTC
When I include a `module-info` in my project (targeting Java 11) the picocli codegen annotation processor fails to execute.  When I remove the `module-info` class it succeeds. 

```txt
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project example: Compilation failure
[ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: picocli.codegen.aot.graalvm.processor.NativeImageConfigGeneratorProcessor Unable to get public no-arg constructor
```

piccolo deps:
```xml
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
            <version>4.1.4</version>
        </dependency>
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli-codegen</artifactId>
            <version>4.2.0</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by remkop** [comment] 2020-04-16 20:35
Thank you for raising this.
The picocli user manual has a section for how to configure your module so that picocli can reflectively access your code: https://picocli.info/#_java_9_jpms_modules

Have you already done this? If so, can you share your `module-info.java`? 
It is possible that this user manual section needs updating to work for the annotation processor...

**Comment by remkop** [comment] 2020-04-16 20:42
Also, that error looks suspiciously like https://github.com/remkop/picocli/issues/773, raised by @triceo, which turned out to be a problem in Intelli/J 2019.2, which was fixed in IntelliJ 2019.2.4.

Does this issue manifest in the IDE (and in that case, which version are you on?), or when you build from the command line?

**Comment by bdemers** [comment] 2020-04-17 14:54
@remkop I noticed that too, I get this error running a clean build on the command line.
I have the expected requires and opens lines, and can run my example without Graal (and picocli-coden)

Is there a way to turn up logging for `picocli-codegen`? I can grab more info.

**Comment by remkop** [comment] 2020-04-17 19:58
@bdemers I would like to try to reproduce the problem. Can you point me to a public repo, or perhaps provide a small project that reproduces the issue?

**Comment by remkop** [comment] 2020-04-17 21:57
About logging in `picocli-codegen`: the `AbstractCommandSpecProcessor` class uses [java.util.logging](https://docs.oracle.com/cd/E23549_01/doc.1111/e14568/handler.htm). 

But I doubt internal `picocli-codegen` logging is going to be useful, because the error indicates we don't even get to this stage:  "picocli.codegen.aot.graalvm.processor.NativeImageConfigGeneratorProcessor Unable to get public no-arg constructor". 

Note that a public constructor does [exist](https://github.com/remkop/picocli/blob/master/picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/processor/NativeImageConfigGeneratorProcessor.java).

So, I suspect that something else is going on. I would investigate by increasing the verbosity of the Maven build, try to isolate the `javac` invocation that is causing the error, and running this `javac` command on the command line, on its own, outside of Maven. Then try to take away things until the error stops occurring, to try to zoom in on the cause.

**Comment by remkop** [comment] 2020-04-19 22:20
@bdemers any updates? Let me know if I can help.

**Comment by bdemers** [comment] 2020-04-20 13:27
@remkop I should have time today (or early tomorrow) to create a minimal example to help you reproduce the issue

**Comment by bdemers** [comment] 2020-04-23 17:46
Hey @remkop sorry about the delay.  I've put together a simple example to reproduce the issue.  I tried to debug it a bit, but I was left scratching my head.

https://github.com/bdemers/picocli-module-info-problem

Depending on how I configure the annotation processing I get different results:
I've set up two profiles in this build, the first (default) shows the problem I've reported.
https://github.com/bdemers/picocli-module-info-problem#add-picocli-codegen-as-a-dependency

The second sets the `annotationProcessorPaths` arg in Maven's Compiler Plugin:
https://github.com/bdemers/picocli-module-info-problem#configure-the-maven-compiler-plugin-explicitly

(this second one fails with and without the `module-info`, i'm not sure if mentioning this is helpful or distracting from the issue I reported)

Thoughts?

**Comment by bdemers** [comment] 2020-04-28 15:18
@remkop I fixed the different version issue, but I'm still running into the same problem

Thanks!

**Comment by remkop** [comment] 2020-04-28 22:53
I was able to get it working on Windows with this `build.bat`:

```
javac ^
   -d target\classes ^
   --module-path %USERPROFILE%\.m2\repository\info\picocli\picocli\4.2.0\picocli-4.2.0.jar;%USERPROFILE%\.m2\repository\info\picocli\picocli-codegen\4.2.0\picocli-codegen-4.2.0.jar ^
   --processor-path %USERPROFILE%\.m2\repository\info\picocli\picocli\4.2.0\picocli-4.2.0.jar;%USERPROFILE%\.m2\repository\info\picocli\picocli-codegen\4.2.0\picocli-codegen-4.2.0.jar ^
   -sourcepath src\main\java;target\generated-sources\annotations ^
   -s target\generated-sources\annotations ^
   -g -nowarn ^
   -verbose ^
   -target 11 ^
   -source 11 ^
   -encoding UTF-8 ^
   --module-version 1.0-SNAPSHOT ^
   src\main\java\org\example\problem\Main.java
```

With this, the `target/classes/META-INF/native-image/picocli-generated/reflect-config.json` file is generated correctly.

It looks like:

* both the `picocli` jar and the `picocli-codegen` jar need to be in the `module-path`
* both the `picocli` jar and the `picocli-codegen` jar need to be in the `processor-path` (the processor-module-path did not work for me)

Without the first, I got "error: module not found: info.picocli.codegen".

Without the second, I got "error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: picocli.codegen.aot.graalvm.processor.NativeImageConfigGenerato
rProcessor Unable to get public no-arg constructor".

I did not try to get the Maven build to work, but I hope 🤞 that this gives some ideas on how to attack that problem... Can you try?

**Comment by remkop** [comment] 2020-05-05 10:44
@bdemers Were you able to make progress on this?

**Comment by remkop** [comment] 2020-05-17 01:35
@bdemers, did you have a chance to look at this?

**Comment by bdemers** [comment] 2020-05-19 16:03
Hey @remkop! Sorry about the delay.

I just tested this again, and everything works fine with Maven when using matching versions of picocil and picocli-codegen as well as configuring picocli-codegen in the `annotationProcessorPath`

I just double-checked the docs, and it DOES say this is how the compiler plugin should be configured. I'm going to say this was caused by user error (and assumptions about how annotation processors get "discovered", and of course my copypasta of the miss-matched versions)

For completeness (future googlers), the compiler plugin config should look something like this, and this IS what the picocli docs say:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>info.picocli</groupId>
                <artifactId>picocli-codegen</artifactId>
                <version>4.2.0</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```

Thanks again for your help!

**Closed** 2020-05-19 16:19 UTC

**Comment by agentgt** [comment] 2023-02-06 18:50
@remkop 

Hey guys just to clarify why this probably happens is that when you have a `module-info.java` in a project Maven will put all the `requires` dependencies on the `module-path`.

All other dependencies that are in maven `<dependencies>` but not in the `module-info.java` will be put on the classpath during compilation. 

Thus if you do the old style of **NOT** using `<annotationProcessorPaths>` you will get

```
info.picocli:picocli -> module-path
info.picocli:picocli-codegen -> classpath
```

picocli-codegen then becomes an automatic module or unnamed one (I think I can't remember which) but regardless it cannot access the core picocli module.

There is way to make this work but it is rather painful. picocli-codegen cannot class load any classes in picocli module which is very much possible by using TypeElement instead of using the raw annotations directly or alternatively shading in picocli into the codegen.

When you do:

```
        <annotationProcessorPaths>
            <path>
                <groupId>info.picocli</groupId>
                <artifactId>picocli-codegen</artifactId>
                <version>4.2.0</version>
            </path>
        </annotationProcessorPaths>
```

You are now putting picocli-codegen on the classpath AND its dependencies (including picocli core since the codegen depends on it) this is technically undesirable but usually benign. Unfortunately you cannot run maven annotation processor on module path: https://issues.apache.org/jira/browse/MCOMPILER-391

However it doesn't really matter because picocli-codegen is not a module which @remkop should fix eventually (either Automatic-Modules-Name or moditect).

Regardless this is still a minor bug (albeit different) or will be eventually if Maven ever fixes MCOMPILER-391.

Let me know if that makes since @remkop

**Comment by remkop** [comment] 2023-02-06 21:32
@agentgt Thank you for the extensive analysis! Hopefully this will help people who encounter this.

FYI, from [picocli 4.7](https://github.com/remkop/picocli/releases/tag/v4.7.0), `picocli-codegen`, and the other published artifacts, are now all full-fledged named JPMS modules. 
(However, I suspect that because of MCOMPILER-391, the solution mentioned in earlier comments remains the same.)

**Comment by agentgt** [comment] 2023-02-06 21:40
@remkop I actually referenced the wrong bug :) I meant this one https://issues.apache.org/jira/browse/MCOMPILER-412

but both are applicable.
