### ISSUE TITLE
Mincronaut app using cli-app profile displays help twice

### ISSUE THREAD

**Issue by datamaskin** [remkop/picocli#465] opened 2018-09-04 19:23 UTC
I created a Micronaut cli runnable-jar app using:
`mn create-cli-app --build maven --test spock dectool`
This app implements runnable and so the Help Options is generated and displayed automatically.
I have to override the defaults in main() (maybe the issue).
Everything works as expected except: java -jar myapp.jar help (displays the formatted help twice).

**Comment by remkop** [comment] 2018-09-04 20:30
Can you show the code for the command? It’s hard to tell what could be the cause otherwise.

**Comment by remkop** [comment] 2018-09-04 21:46
One thing: if your command is defined with `mixinStandardHelpOptions = true`, the `-h` and `--help` options are automatically added to the command. 

However, when invoking the command with `java -jar myapp.jar help`, picocli will think the `help` argument (without leading dashes) is a positional parameter or a subcommand. 

To trigger help, specify `--help` instead of `help`: so invoke with `java -jar myapp.jar --help`. 

That doesn’t explain why you’re seeing the usage help message twice though, I’d need to see the code to say more.

**Comment by remkop** [comment] 2018-09-05 23:56
@datamaskin  Hi, is this still an issue?

**Comment by datamaskin** [comment] 2018-09-06 00:19
Howdy Remko,

First of all allow me to thank you for an excellent CLI framework.

Much better than the Apache stuff.

Yes, I removed the mixin before posting in GitHub but no help.

The issue is minor and otherwise my application is running correctly.

I think I know what the issue is but as you say the source is the best 
answer.

Actually, I am very interested in helping to create the Intellij plugin 
for pico.

I have an Ultimate license and have used IDEA for many years but have 
not created any plugins.

Not sure you will get this as I have been experiencing TLS cert issues 
with my email server.

I will read more the Jetbrains doco on plugins and get back soon.

Thanks.

**Comment by remkop** [comment] 2018-09-06 01:15
Hi David, glad you like picocli!

Great to hear you’re interested in working on #460 (intelli/j plugin)! That ticket currently just has some early thoughts, happy to chat further there to flesh things out if you want. 

About this ticket: sounds like it’s still a problem. Can you show the source of the command?

**Comment by remkop** [comment] 2018-09-14 12:17
@datamaskin  Is this still an issue? If you want me to help, can you show the source of the command? Otherwise, can this ticket be closed?

**Comment by remkop** [comment] 2018-09-20 05:00
Closing this ticket. Feel free to re-open with more information in order to investigate.

**Closed by remkop** 2018-09-20 05:00 UTC
