### ISSUE TITLE
Exclusive argument groups disappear when using native-image

### ISSUE THREAD

**Issue by mikehearn** [remkop/picocli#793] opened 2019-08-23 16:49 UTC
I have the following code:

```
    static class Mode {
        @CommandLine.Option(names = {"-e", "--encrypt"}, required = true) boolean encrypt;
        @CommandLine.Option(names = {"-d", "--decrypt"}, required = true) boolean decrypt;
    }

    @CommandLine.ArgGroup(exclusive = true, multiplicity = "1")
    Mode mode;
```

This works as expected on HotSpot. When using the annotation processor and native-imaeg, the -e and -d options vanish from the help output and trying to access mode throws an NPE. It's like PicoCLI just forgets all about the mode parameter entirely, but the other params are still there!

I checked the generated JSON files and they look reasonable. Mode and the options are there. Seems something goes wrong at runtime.

**Comment by remkop** [comment] 2019-08-23 22:40
Thanks for raising this!
Can you share the results of running the native image with `-Dpicocli.trace=DEBUG`?

**Comment by remkop** [comment] 2019-08-24 03:27
I've been able to reproduce the problem.
I believe the generated reflection-info JSON is missing the group field, still investigating.

**Comment by remkop** [comment] 2019-08-24 07:12
The problem was that the generated reflect-config.json was missing the `@ArgGroup`-annotated fields.

I've pushed a fix to master, and will do a release for this soon.

**Comment by mikehearn** [comment] 2019-08-24 13:05
Thanks! Amazingly fast work!

**Closed** 2019-08-26 12:19 UTC
Labels: bug

**Comment by remkop** [comment] 2019-08-26 15:54
Picocli 4.0.3 which includes a fix for this issue has been released and should be available from Maven Central in a few hours.

Thanks again for the bug report!

**Comment by remkop** [comment] 2019-08-28 01:26
@mikehearn It would be great if you could confirm that picocli 4.0.3 fixes the issue.

**Comment by mikehearn** [comment] 2019-08-28 09:45
It works! Thanks again.

**Comment by remkop** [comment] 2019-08-28 09:52
Excellent!
Please star picocli on GitHub if you like the project and tell your friends!
