### ISSUE TITLE
ArgGroup options default value is null in usage help message

### ISSUE THREAD

**Issue by galaxyrise** [remkop/picocli#839] opened 2019-10-17 21:24 UTC
I'm organizing my code using multiple '@ArgGroup (validate = false, heading = "BlahBlah")' sections.  Unfortunately, Options inside ArgGroups with '(default: ${DEFAULT-VALUE})' in the description always report the default as null. 

_EDIT: Note to future readers, ignore the rest of this message, I simply did not understand the formatting convention_

Also, I have a more minor issue with 'help' text: the indentation of the options is inconsistent in some cases*.  The example below results in different indentation for the two options (identation reverts to normal if I change '-yy' to '-y'.

```
	@Option(names = {"-z"}, description = "...")
	String z;
	@Option(names = {"-yy"}, description = "...")
	String y;
```

_\* In my original 'Issue' I said this was specific to ArgGroups and/or booleans... this was proven untrue by my later testing, hence the update with the example code_

P.S.  Issues aside, this is wonderful software!

**Comment by remkop** [comment] 2019-10-17 22:30
The usage help message has separate columns for posix short options and for long options. A posix short option has a single hyphen followed by a single character. Anything else is considered a long option. This is consistent with how most Unix utilities work. 

About the problem with the default value, can you give an example to reproduce the issue? I’ll take a look when I get to my pc.

**Comment by remkop** [comment] 2019-10-17 22:40
And thanks for raising this issue! :-)

**Comment by galaxyrise** [comment] 2019-10-17 23:00
Thanks.  Here is the requested sample code to reproduce the default value issue:

```
import java.util.concurrent.Callable;
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(mixinStandardHelpOptions = true)
public class CliTest implements Callable<Void> {

	@ArgGroup(validate = false, heading = "== ArgGroup ==%n")
	Section1 test;

	static class Section1 {
		@Option(names = { "-a"}, description = "Inside ArgGroup default: ${DEFAULT-VALUE}")
		String testDefault = "myDefault";
	}

	@Option(names = { "-b"}, description = "Outside ArgGroup default: ${DEFAULT-VALUE}")
	String testDefault = "myDefault";
	
	@Override
	public Void call() throws Exception {
		return null;
	}

	public static void main(String[] args) {
		new CommandLine(new CliTest()).execute(new String[] {"-h"});		
	}
}
```

Here is the resulting output:

```
Usage: <main class> [-hV] [-a=<testDefault>] [-b=<testDefault>]
  -b=<testDefault>    Outside ArgGroup default: myDefault
  -h, --help          Show this help message and exit.
  -V, --version       Print version information and exit.
== ArgGroup ==
  -a=<testDefault>    Inside ArgGroup default: null

```

**Comment by remkop** [comment] 2019-10-18 03:40
Thanks for the example code; it illustrates the inconsistency very well.

You can work around this by specifying the default value in the annotation instead of in the field initial value. That will correctly show the default value in the usage help message. For example:

```java
static class Section1 {
  @Option(names = "-a", defaultValue = "myDefault",
          description = "Inside ArgGroup default: ${DEFAULT-VALUE}")
  String testDefault;
}
```

I'm still thinking about how to solve this.

The reason why this is happening is that picocli does not create an instance of the `@ArgGroup`-annotated class (`Section1` in your example) until an option in that group is matched. Without an instance of `Section1`, picocli cannot obtain the value of the `testDefault` field.

For `@Command`-annotated classes, picocli _does_ instantiate the user object during initialization, so options outside an `ArgGroup` can read the default value from the field initial value.

Your use case demonstrates that this approach has drawbacks.

I need to take another look at the initialization logic. There is a related request to [lazily initialize](https://github.com/remkop/picocli/issues/690) `@Command`-annotated classes; maybe I can address both these issues at the same time. This will take some time. Meanwhile, I hope the workaround described above will address your immediate needs.

**Comment by galaxyrise** [comment] 2019-10-18 03:59
Many thanks, the workaround will be just fine for my needs.

**Comment by remkop** [comment] 2019-10-18 04:02
Glad to hear that!
If you like picocli, please star the project on GitHub and tell your friends! :-)

**Comment by galaxyrise** [comment] 2019-10-18 20:19
Sorry, one other related request.  Is there a way to force instantiation ArgGroup static classes?  Otherwise their utility is greatly diminished as one always has to check for nulls and has no access to default values.

**Comment by remkop** [comment] 2019-10-18 23:01
> Is there a way to force initialization of ArgGroup static classes?

Yes, the application can assign an instance to the `@ArgGroup`-annotated field:

```java
@Command(mixinStandardHelpOptions = true)
public class CliTest implements Callable<Void> {

    @ArgGroup(validate = false, heading = "== ArgGroup ==%n")
    Section1 test = new Section1();  // <-- ensure that `test` is never null

    static class Section1 {
        @Option(names = { "-a"}, description = "Inside ArgGroup default: ${DEFAULT-VALUE}")
        String testDefault = "myDefault";
    }
	
    @Override
    public Void call() throws Exception {
        System.out.printf("testDefault=%s%n", test.testDefault); // no null checks needed
        return null;
    }
...
```
> "required = true" is not honored if a command is in an ArgGroup

About your other question, "required = true" in an ArgGroup means that the option is required _within the ArgGroup_.  To make the group _itself_ required, use `multiplicity`. For example:

```java
@Command(name = "co-occur")
public class DependentOptionsDemo {

    @ArgGroup(exclusive = false, multiplicity = "1") // group must occur exactly once
    Dependent dependent;

    static class Dependent {
        @Option(names = "-a", required = true) int a;
        @Option(names = "-b", required = true) int b;
        @Option(names = "-c", required = false) int c;
    }
}
```

This defines a group of options that are mutually dependent (they must co-occur). The group is defined with `multiplicity = "1"`, so validation will fail if the group is not specified exactly once. Within the group, the `-a` and `-b` options are required, and `-c` is optional. So the following inputs are legal:

```
# these are valid input
co-occur -a=1 -b=2
co-occur -a=1 -b=2 -c=3
```

While these inputs are invalid:

```
# invalid: missing the required group
co-occur

# invalid: missing required option -b
co-occur -a=1

# invalid: group specified more than once
co-occur -a=1 -b=2 -a=11 -b=22
```

Does this meet your requirements?

**Comment by remkop** [comment] 2019-10-18 23:06
By the way, feel free to open separate tickets for different questions.  That makes it easier to track for me if the question results in some follow-up action for me. :-)

**Comment by galaxyrise** [comment] 2019-10-19 00:17
Thanks again, and apologies for my confusion!

**Comment by remkop** [comment] 2019-10-19 01:18
NO problem at all. Enjoy picocli!

**Comment by remkop** [comment] 2019-11-01 01:07
I added a new section [Default Values in Argument Groups](https://picocli.info/#_default_values_in_argument_groups) to the user manual and clarified that the `defaultValue` annotation is the preferred way to [define defaults](https://picocli.info/#_default_values).

**Comment by remkop** [comment] 2019-11-04 22:26
I'll close this issue, I don't think there is any work remaining on this now.
Feel free to re-open or open a new ticket if there is any problem.

**Closed by remkop** 2019-11-04 22:26 UTC
Labels: arg-group, doc, enhancement
