### ISSUE TITLE
Create empty Map for Map @Option in command methods

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#533] opened 2018-10-28 14:47 UTC
Currently the following will result in a `null` `Map` being passed to the method:

```java
public Status exec(@Option(names = "-e", description = "Environmental variables in key=value format") Map<String, String> vars) {
// ...
}
```

From the docs:

> If the field is null, picocli will instantiate it when the option or positional parameter is matched. If the type is not a concrete class, picocli will instantiate a LinkedHashMap to preserve the input ordering.

However this is isn't a field so the expectation is unclear. Ideally this would be initialized to an empty Map. Updating the documentation to account for command methods would also be useful.

**Comment by remkop** [comment] 2018-10-31 23:51
@bobtiernay-okta Does this answer your question?

**Comment by bobtiernay-okta** [comment] 2018-11-01 01:46
Yes it does thanks. Sorry, I planned to say I would help add a note to the docs. Might be able to get to it later in the week. Thanks!

**Comment by remkop** [comment] 2018-11-01 02:56
That would be great, thanks!

**Comment by bobtiernay-okta** [comment] 2018-11-02 14:08
So I'm trying to update the documentation but I'm struggling to square the existing docs:

> If the field is null, picocli will instantiate it when the option or positional parameter is matched

with your comment above:

> The convention in picocli is to not modify annotated fields (or parameters) that weren’t matched on the command line, unless a default value was specified.

In the case of an `@Option` that is on a command method parameter without a `defaultValue` specified, should't the behavior be to create it per the first sentence above?

**Comment by remkop** [comment] 2018-11-02 22:02
I created a test to demonstrate the current behaviour and actually found a bug. :-) The test is in the issue I created: https://github.com/remkop/picocli/issues/538

The test shows the expected behaviour:

* if no options are matched, method parameters without a default will have a `null` value, while method parameters with a default will have the default value
* if options are matched, the matched value is passed to the method

In the case of fields, it's similar, but slightly more complex because fields can have an initial value in their declaration, for example:

```
@Option(names = "-x")
Integer x = 123;
```

* if the option is not matched, annotated fields without a default will be set to their initial value, and annotated fields with a default will be set to the default value. Instead of "are not modified" it's more accurate to say "are reset to the initial value".
* if the option is matched, annotated fields are set to the matched value. For multiple values that may be a `List`, and picocli will instantiate the `List` unless the field already has a non-`null` value:

```
@Option(names = "-y")
List<String> y = null; // picocli creates a List instance if -y is matched

@Option(names = "-z")
List<String> z = new ArrayList<>(); // picocli adds to this existing instance if -z is matched
```

**Comment by remkop** [comment] 2018-11-09 17:01
Did my last comment answer your question?

**Comment by remkop** [comment] 2018-11-10 07:43
Early warning: I’m planning to do a release in a week or so. If you can provide any doc improvements this week they will be included in the upcoming release. Of course there will be other releases if that’s too soon.

**Comment by bobtiernay-okta** [comment] 2018-11-11 01:16
Will try to get to this tomorrow or Monday.

**Comment by remkop** [comment] 2018-11-11 23:06
Hi @bobtiernay-okta, I saw the PR on #545, thank you! Is this ready to be merged and are you happy to close this ticket when #545 is merged or are there more changes in the pipeline?

**Comment by bobtiernay-okta** [comment] 2018-11-11 23:48
I think its good enough for now. I was going to add more detail but it really didn't fit in that section. I'll try to contribute a more substantial piece next time!

**Comment by remkop** [comment] 2018-11-12 01:52
Understood. I merged to PR. Do you want to keep this ticket open?

**Closed** 2018-11-12 22:11 UTC
Labels: doc, enhancement
