### ISSUE TITLE
Method arg values not iterated correctly in CommandSpec#commandMethodParamValues

### ISSUE THREAD

**Issue by Onedy** [remkop/picocli#1741] opened 2022-07-13 22:06 UTC
Hi,

I am getting  an `IllegalArgumentException: argument type mismatch` when I input this command: `sorteo enter compound tweeturl`
Where `sorteo` and `enter` are nested subcommands that inherit `mixinStandardHelpOptions = true` from a parent command annotated with:
```
@CommandLine.Command(mixinStandardHelpOptions = true, scope = CommandLine.ScopeType.INHERIT)
```
and `compound` and `tweeturl` are parameters. The issue is that these two parameters are retrieved as booleans when they are defined as String:
```
@CommandLine.Command(name = "enter")
void enter(@CommandLine.Parameters(arity = "1") String sentenceType,
           @CommandLine.Parameters(arity = "1") String tweetUrl) {...}
```
This is happening because when the call stack gets to `commandMethodParamValues`
![Captura de pantalla 2022-07-13 a las 23 01 01](https://user-images.githubusercontent.com/12222433/178834296-a2c0e292-913f-4be9-af80-c56332e5e9a4.png)
![Captura de pantalla 2022-07-13 a las 22 59 56](https://user-images.githubusercontent.com/12222433/178838297-4f8c978f-0302-4458-87de-d0d976e3f7cf.png)

the line
```
int argIndex = autoHelpMixin == null || autoHelpMixin.inherited() ? 0 : 2;
```
 makes this line from the else
```
values[i] = args.get(argIndex++).getValue();
```
to retrieve the values of the mixinStandardHelpOptions insetead of the actual parameters, because `argIndex` starts at 2 as you can see in the variables pane:
![Captura de pantalla 2022-07-13 a las 23 00 46](https://user-images.githubusercontent.com/12222433/178838498-c0aa45b5-fbfe-44f8-8272-bcc8d937cdac.png)
![Captura de pantalla 2022-07-13 a las 23 58 12](https://user-images.githubusercontent.com/12222433/178843828-509c7ebc-60a5-497d-951d-9b7ae4ed780c.png)

Am I doing something wrong?

**Comment by remkop** [comment] 2022-07-14 05:19
Hi @Onedy, thank you for raising this.
I tried but was unable to reproduce the issue. Maybe you can help me create a minimal test case that demonstrates the issue.

I had to guess and this is the test code I ended up with:

```java
// in some JUnit test class

@Command(name = "app", mixinStandardHelpOptions = true, scope = INHERIT, subcommands = Sorteo.class)
static class TestIssue1741 implements Runnable {
    @Override public void run() {
        System.out.println("Executing top-level command");
    }
}
@Command(name = "sorteo")
static class Sorteo implements Runnable {
    @Command(name = "enter")
    void enter(@Parameters(arity = "1") String sentenceType,
               @Parameters(arity = "1") String tweetUrl) {
        System.out.printf("Subcmd 'enter' was called with %s and %s%n", sentenceType, tweetUrl);
    }

    @Override public void run() {
        System.out.println("Executing command 'sorteo'");
    }
}

@Test
public void testIssue1741() {
    new CommandLine(new TestIssue1741()).execute("sorteo", "enter", "compound");
}

@Test
public void testIssue1741b() {
    new CommandLine(new TestIssue1741()).execute("sorteo", "enter", "sentenceType1", "tweetURL2");
}
```

When I run `testIssue1741`, I see this output:
```
Missing required parameter: '<arg1>'
Usage: app sorteo enter [-hV] <arg0> <arg1>
```

When I run `testIssue1741b`, I see this output:
```
Subcmd 'enter' was called with sentenceType1 and tweetURL2
```

Can you help massage this test into something that demonstrates the issue?

**Comment by Onedy** [comment] 2022-07-14 07:58
I think the issue appears when the Spring factory is used. Here you have a minimal test:

```java
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;
import picocli.CommandLine;

import java.util.List;

import static picocli.CommandLine.ScopeType.INHERIT;

@Configuration
class Config {

    @Bean
    public CommandLine getTestCommandLine(ParentCommand parentCommand, List<Command> commands, CommandLine.IFactory factory) {
        CommandLine commandLine = new CommandLine(parentCommand, factory);
        commands.forEach(commandLine::addSubcommand);
        return commandLine;
    }
}

@Component
@CommandLine.Command(name = "parentTestCommand", mixinStandardHelpOptions = true, scope = INHERIT)
class ParentTestCommand {
}

@Component
@CommandLine.Command(name = "sorteotest")
class TestCommand {
    @CommandLine.Command(name = "entertest", description = "Start participating in a giveaway")
    void enter(@CommandLine.Parameters(arity = "1") String sentenceType,
               @CommandLine.Parameters(arity = "1") String tweetUrl) {
        System.out.println("entering giveaway");
    }
}

@SpringBootTest
class MyTest {

    @Autowired
    private ParentTestCommand parentTestCommand;

    @Autowired
    @Qualifier("getTestCommandLine")
    private CommandLine commandLine;

    @org.junit.jupiter.api.Test
    void testIssue1741() {
        commandLine.addSubcommand(new TestCommand());
        commandLine.execute("sorteotest", "entertest", "sequenceType", "url");
    }
}
```

**Comment by Onedy** [comment] 2022-07-15 09:41
Hi @remkop, were you able to reproduce this issue?

**Comment by remkop** [comment] 2022-07-15 11:25
Hi @Onedy, no I haven't...
I got a NullpointerException in `testIssue1741()` method because the `commandLine` field is null. 

Can you provide an example that doesn't use Spring, or alternatively an example that I can copy into the `picocli-spring-boot-starter` module (maybe under [test](https://github.com/remkop/picocli/tree/main/picocli-spring-boot-starter/src/test/java/picocli/spring)) to reproduce the issue?
runs as a test

**Comment by Onedy** [comment] 2022-07-17 12:06
Hi @remkop, I couldn't build the `picocli-spring-boot-starter` module because I couldn't get resources from https://repo.spring.io/libs-snapshot, but I've created a minimal project where you can execute the test:

[PicocliTest.zip](https://github.com/remkop/picocli/files/9127559/PicocliTest.zip)

Just unzip and run with `./gradlew clean assemble :test --tests "test.MyTest" --info`
And look at:
```
MyTest > testIssue1741() STANDARD_ERROR
    java.lang.IllegalArgumentException: argument type mismatch
```

**Comment by remkop** [comment] 2022-07-19 08:51
@Onedy Great thank you!
I was able to reproduce the issue now, even without Spring.
[This](https://github.com/remkop/picocli/blob/675327cce7c8dc5cd19b85fbaf7c06fa14116f67/src/test/java/picocli/Issue1471.java) demonstrates that the issue is in picocli.
It appears to have something to do with the subcommand being added later with `commandLine.addSubcommand(testCommand)`. Still investigating...

**Comment by remkop** [comment] 2022-07-22 10:02
I found the cause:
When a subcommand with a nested sub-subcommand is added later with `commandLine.addSubcommand`, there is some logic that takes place that initializes the `inherited` state for the whole hierarchy and makes sure that the standard help options are mixed in by inheritance. 
However, the method for mixing in the standard help options in the hierarchy itself also goes down the hierarchy. 
As a result, the `sorteotest` CommandSpec has inherited=true, but the `entertest` subcommand still has `inherited=false` when the standard help option mixin is added. This makes a difference for the position of the arguments of the command method.

**Comment by remkop** [comment] 2022-07-22 10:08
I fixed the bug in the main branch and the fix will be included in the next release.
Thank you again for raising this!

**Closed** 2022-07-22 10:08 UTC

**Comment by Onedy** [comment] 2022-08-08 19:17
Thank you for the fix!
