### ISSUE TITLE
Options defined on parent command appear to not be assignable to values of registered subcommand names

### ISSUE THREAD

**Issue by turnef** [remkop/picocli#1538] opened 2022-01-01 23:32 UTC
I may be making a mistake or perhaps my expectations are misguided, but it appears that in some cases single-valued type options are unable to be assigned values of registered subcommand names.  The following simple example demonstrates the issue:
```java
import java.nio.file.Path;
import java.util.concurrent.Callable;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "clitest", subcommands = {CliTest.Subset.class})
public class CliTest implements Callable<Integer> {

  @Option(names = "-output", defaultValue = ".")
  Path output;

  public Integer call() {
    return 1;
  }

  public static void main(String[] args) {
    CommandLine cmdLine = new CommandLine(new CliTest());
    // Works as expected
    cmdLine.execute("-output", "test", "subset");
    // Fails with: Expected parameter for option '-output' but found 'subset'
    cmdLine.execute("-output=subset", "subset");
    // Fails with: Expected parameter for option '-output' but found 'subset'
    cmdLine.execute("-output", "subset", "subset");
  }

  @Command(name = "subset")
  static class Subset implements Callable<Integer> {
    public Integer call() {
      System.out.println("Executed successfully");
      return 0;
    }
  }
}
```
My expectations were that at least one of the two failures in the main method would have succeeded in assigning the Path field output to the value of subset.  

Thanks in advance for any suggestions or thoughts on how I might handle this situation.

**Comment by remkop** [comment] 2022-01-02 08:40
Hi @turnef, thank you for raising this!
I believe this issue is a duplicate of https://github.com/remkop/picocli/issues/1125, am I correct?

Perhaps the best way currently available to deal with this is to set a [parameter consumer](https://picocli.info/#_iparameterconsumer_parser_plugin) or a [parameter preprocessor](https://picocli.info/#IParameterPreprocessor_Parser_Plugin) on the option. Issue #1125 has an example. However, this is not mentioned in the documentation.

I will update the [section in the documentation](https://picocli.info/#_option_names_as_option_values) for this to clarify that not just option names, but also subcommand names are not accepted as option values out of the box, and provide an example of how to deal with this.

**Comment by remkop** [comment] 2022-01-02 09:45
I modified this section of the manual: https://picocli.info/#_option_names_or_subcommands_as_option_values

it now has Java and Kotlin examples of using a parameter processor for this use case.
Feedback welcome.

**Closed by remkop** 2022-01-02 09:45 UTC
Labels: duplicate, doc

**Comment by turnef** [comment] 2022-01-02 20:45
@remkop, thanks for your response.  Yes, this is a duplicate of #1125, and please accept my apologies for posting it.  I should have taken the time to read through the existing issues first.  The custom parameter processor example you added in the documentation solves the specific problem I have quite nicely.  Thanks again for your time and advice.

**Comment by remkop** [comment] 2022-01-02 22:26
@turnef no need to apologize! 
I should thank you, you are not the first to mention this, and you nudged me to finally improve the user manual. 😅 
Enjoy using picocli!
