### ISSUE TITLE
Autocompletion for help command

### ISSUE THREAD

**Issue by qw3ry** [remkop/picocli#693] opened 2019-05-14 09:22 UTC
When registering `HelpCommand.class` as `subcommand`, no autogeneration for the help on other subcommands is generated.

Current behaviour: typing `mycommand help <TAB><TAB>` falls back to default autocompletion
Expected behaviour: registered commands are shown as candidates for autocompletion

Some ideas off the top of my head:
- treat the `HelpCommand` as special case in the completion generation
- modify the `HelpCommand` to register subcommands (works only for runtime help generation)
- require some custom subclassing of the help command with specification of the possible completions (is this possible?)

**Comment by remkop** [comment] 2019-05-14 13:01
I never realized, but you’re right. 
To address this, I like the first option you mentioned best (Autocompletion logic to give special treatment to `HelpCommand`).

Will you be able to provide a pull request for this?

**Comment by qw3ry** [comment] 2019-05-15 09:11
I cannot do this during work-time as this is something that is not important to my employee.
IF I find the time, I can look into it in my spare time. If I start working on this, I'll let you know here. But do not expect something soon. Sorry :(

**Comment by remkop** [comment] 2019-05-15 10:09
Ok, cool! Contributions always welcome!

**Comment by NewbieOrange** [comment] 2020-04-26 06:43
I added the special case for HelpCommand in autocompletion generation in PR #1009 .

It also includes a new test, not sure whether the new behaviour is as intended, but it should not break any previous tests.

**Comment by remkop** [comment] 2020-04-27 10:48
@NewbieOrange I merged the PR into master.
Thank you for the contribution!

It would be great if you could also add an Expect test for the new completions to the [dejagnu.tests](https://github.com/remkop/picocli/tree/master/src/test/dejagnu.tests).

This would be similar to the [picocompletion.exp](https://github.com/remkop/picocli/blob/master/src/test/dejagnu.tests/completion/picocompletion.exp) and [picocompletion-demo.exp](https://github.com/remkop/picocli/blob/master/src/test/dejagnu.tests/lib/completions/picocompletion-demo.exp), but for the new `src/test/resources/picocompletion-demo-help_completion.bash` completion script you added. 

Do you think you will be able to do that?

**Comment by NewbieOrange** [comment] 2020-04-27 11:27
Glad I could help. I've add a dejagnu test picocompletion-help.exp and picocompletion-demo-help.exp in #1011 .

**Comment by remkop** [comment] 2020-04-29 11:06
All merged.
Thank you again for the contributions! Nice work!

**Closed** 2020-04-29 11:05 UTC
Labels: auto-completion, codegen, enhancement, shell
