### ISSUE TITLE
@Mixin on command method parameter within command class in hierarchy causes DuplicateOptionAnnotationsException

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#552] opened 2018-11-19 14:36 UTC
I'm hitting the following exception:

> A member cannot be both a @Mixin command and an @Option or @Parameters, but 'public Status MyCommand.status(AbstractCommand$StatusOptions):arg0' is both.

For a setup that follows this general pattern:

```java
public abstract class AbstractCommand implements Callable<Status> {
    protected Status status(@Mixin StatusOptions options) {
        // ...
    }

    protected static class StatusOptions {
        @Option(names = "--extended")
        public boolean extended;
    }
}

@Command(name = NAME, description = "My command")
public class MyCommand extends MyCommand {
    @Override
    @Command(description = "Perform a status check")
    public Status status(@Mixin StatusOptions options) {
        return super.status(options);
    }
}
```

Full stack trace:
```
Exception in thread "main" picocli.CommandLine$DuplicateOptionAnnotationsException: A member cannot be both a @Mixin command and an @Option or @Parameters, but 'public Status MyCommand.status(AbstractCommand$StatusOptions):arg0' is both.
    at picocli.CommandLine$Model$CommandReflection.validateMixin(CommandLine.java:5985)
    at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:5948)
    at picocli.CommandLine$Model$CommandReflection.initFromMethodParameters(CommandLine.java:5979)
    at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:5854)
    at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3580)
    at picocli.CommandLine.<init>(CommandLine.java:185)
    at picocli.CommandLine.<init>(CommandLine.java:164)
    at picocli.CommandLine$Model$CommandSpec.addMethodSubcommands(CommandLine.java:3729)
    at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:5906)
    at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5886)
    at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5870)
    at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:5840)
    at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3580)
    at picocli.CommandLine.<init>(CommandLine.java:185)
    at picocli.CommandLine.toCommandLine(CommandLine.java:2254)
    at picocli.CommandLine.access$8300(CommandLine.java:142)
    at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:5893)
    at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5886)
    at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5870)
    at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:5840)
    at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3580)
    at picocli.CommandLine.<init>(CommandLine.java:185)
    ...
```

My suspicion is that this has something to do with the enclosing class hierachy and use of overriden methods.

I will try to create a simple example to reproduce outside of my current private project.

**Comment by remkop** [comment] 2018-11-19 15:35
I don’t understand this fully yet but it sounds like a bug.

**Comment by remkop** [comment] 2018-11-20 08:06
I am unable to reproduce this. The test below passes without issues:

```java
class ComplexHierarchyText {
    abstract class AbstractCommand implements Callable<Integer> {
        protected Integer status(@Mixin StatusOptions options) {
            return options.extended ? 456 : 789;
        }

        protected static class StatusOptions {
            @CommandLine.Option(names = "--extended")
            public boolean extended;
        }
    }

    @Command(name = "top", description = "My command")
    class MyCommand extends AbstractCommand {
        @Override
        @Command(description = "Perform a status check")
        public Integer status(@Mixin AbstractCommand.StatusOptions options) {
            return super.status(options);
        }

        @Override
        Integer call() throws Exception {
            return 123;
        }
    }

    @Test
    public void testComplexHierarchy() {
        Integer statusExtended = CommandLine.call(new MyCommand(), "status", "--extended");
        assertEquals(456, statusExtended);

        Integer status = CommandLine.call(new MyCommand(), "status");
        assertEquals(789, status);

        Integer topLevelResult = CommandLine.call(new MyCommand());
        assertEquals(123, topLevelResult);
    }
}
```

**Comment by remkop** [comment] 2018-11-21 03:16
Have you been able to isolate the cause? I have not been able to make progress on this since I cannot reproduce it.

**Comment by remkop** [comment] 2018-11-21 12:49
No problem at all!
I'll close this ticket then. Feel free to reopen if it happens again.

**Closed by remkop** 2018-11-21 12:49 UTC
