### ISSUE TITLE
allow option with a default the same as a subcommand name

### ISSUE THREAD

**Issue by cbcmg** [remkop/picocli#1428] opened 2021-09-08 04:58 UTC
Hi, I would like to have an option available to all subcommands that happens to have a default value which is also the name of a subcommand. This currently fails due to the argSpec failing varargCanConsumeNextValue(). I'm not sure if this is by design or a limitation, or a bug. Here is a reproduction. Thanks

```kotlin
import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Option
import picocli.CommandLine.ParentCommand
import java.util.concurrent.Callable

@Command(
  name = "portal",
  subcommands = [AdminCmd::class],
  mixinStandardHelpOptions = true,
)
class PortalCmd : Callable<Int> {

  @Option(
    names = ["--username"],
    defaultValue = "admin",
    scope = CommandLine.ScopeType.INHERIT
  )
  var username: String? = null

  override fun call(): Int {
    return 0;
  }
}

@Command(
  name = "admin",
  mixinStandardHelpOptions = true,
)
class AdminCmd : Callable<Int> {
  @ParentCommand
  lateinit var portal: PortalCmd

  override fun call(): Int {
    println("username=${portal.username}")
    return 0;
  }
}

fun main(args: Array<String>) {
  CommandLine(PortalCmd()).execute("admin", "--username=test") // works!
  CommandLine(PortalCmd()).execute("admin", "--username", "test") // works!
  CommandLine(PortalCmd()).execute("admin", "--username=admin") // works!
  CommandLine(PortalCmd()).execute("admin", "--username", "admin") // works!
  CommandLine(PortalCmd()).execute("admin") // fails with "Expected parameter for option '--username' but found 'admin'"
}
```

**Comment by remkop** [comment] 2021-09-08 06:41
Hi @cbcmg, I believe this is a duplicate of https://github.com/remkop/picocli/issues/1125

Can you check if the workaround suggested in #1125 helps to alleviate the problem for you?
Basically, the idea is to give that option a `parameterConsumer` that takes care of assigning the value to the option.

Roughly, something like this:

```java
class PortalCmd : Callable<Int> {

  @Option(
    names = ["--username"],
    parameterConsumer = MyParameterConsumer::class,
    defaultValue = "admin",
    scope = CommandLine.ScopeType.INHERIT
  )
  var username: String? = null
...
}

class MyParameterConsumer : IParameterConsumer {
    override fun consumeParameters(args: Stack<String>, argSpec: ArgSpec, commandSpec: CommandSpec) {
        if (args.isEmpty()) { // this check may be unnecessary
            throw ParameterException(commandSpec.commandLine(),
                    "Missing required parameter for option " + ((OptionSpec) argSpec).longestName());
        }
        argSpec.setValue(args.pop());
    }
}
```

**Comment by cbcmg** [comment] 2021-09-08 06:51
Yep, that did the trick. Sorry for my terrible search skills. And thanks for a terrific library!!

**Comment by remkop** [comment] 2021-09-08 07:20
No worries. 

Maybe this should be added to the documentation; I don’t see myself working on that issue in the near future…

Do you feel like contributing a PR to the documentation?

**Closed** 2021-09-28 01:35 UTC
Labels: duplicate, doc
