### ISSUE TITLE
Parameter validates an unknown option

### ISSUE THREAD

**Issue by jcapsule** [remkop/picocli#282] opened 2018-02-07 00:00 UTC
Using only one field with `@Parameter` with an arity of `"1..*"` is considering an unknown option as a valid parameter.

Example to reproduce:
```java
import picocli.CommandLine;
import picocli.CommandLine.Parameters;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class App implements Runnable {
    @Parameters(paramLabel = "FILES", arity = "1..*", description = "List of files")
    private List<File> files = new ArrayList<>();

    // Uncomment to validate @Parameter arity = "1..*",
    //    @CommandLine.Option(names = {"-v"}, description = "Print output")
    //    private boolean verbose;

    public static void main(String[] args) {
        args = new String[]{"-unknown"};

        CommandLine.run(new App(), System.out, args);
    }
    @Override
    public void run() {
        System.out.println("DONE");
    }
}
```
Excepted:

Return the message of missing required parameters.

**Comment by remkop** [comment] 2018-02-07 02:05
Thanks for the bug report! I was able to reproduce the issue. Still investigating the cause...

**Comment by remkop** [comment] 2018-02-07 14:29
This is now fixed in branch r2.2.x.
I created a release v2.2.2 for this. The release is available on GitHub now, and should be available on Maven Central and Bintray soon.

Please verify.

**Closed by remkop** 2018-02-07 14:29 UTC

**Comment by jcapsule** [comment] 2018-02-07 21:42
Fixed. Tks.

**Comment by remkop** [comment] 2018-02-07 22:33
Thanks for the confirmation and thanks again for the bug report! Keep ‘em coming!
