### ISSUE TITLE
Invalid error message generated when unmatched positional argument is the same as one of previous valid argument

### ISSUE THREAD

**Issue by vi** [remkop/picocli#1225] opened 2020-10-23 21:10 UTC
```
$ java -jar  app.jar   sdf sf sdf
Unmatched argument at index 0: 'sdf'
Usage: app [-hV] <arg1> <arg2>
...
```

```
$ java -jar  app.jar   sdf sf qqq
Unmatched argument at index 2: 'qqq'
Usage: app [-hV] <arg1> <arg2>
...
```

Expected them to be both "index 2".

Version 4.5.2.

**Comment by remkop** [comment] 2020-10-23 21:16
Can you share your code so I can try to reproduce the issue?

**Comment by vi** [comment] 2020-10-23 21:35
Approximate redacted source code:

```java

import picocli.CommandLine;

import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;
import java.util.concurrent.Callable;

@Command(name = "app", mixinStandardHelpOptions = true, version = "app 1.0",
         description = "....")
public class App implements Callable<Integer> {

    @Parameters(index = "0", description = "...")
    private String arg1;

    @Parameters(index = "1", description = "...", defaultValue="")
    private String arg2;

    @Override
    public Integer call() throws Exception {
        return 0;
    }
    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}

```

(not checked buildability)

**Comment by remkop** [comment] 2020-10-23 23:38
I tried but I am unable to reproduce the issue.

Can you look at this test code: https://github.com/remkop/picocli/blob/master/src/test/java/picocli/Issue1225.java
and suggest changes so that I can reproduce the issue?

**Comment by vi** [comment] 2020-10-23 23:58
First and third elements of the array should match to make it err.

**Comment by remkop** [comment] 2020-10-24 07:02
Yes, now I can reproduce it. Thank you for pointing this out!

I renamed the test to https://github.com/remkop/picocli/blob/master/src/test/java/picocli/Issue1225UnmatchedArgBadIndex.java

I found the cause and pushed a fix to master. This will be included in the next release.

**Closed by remkop** 2020-10-24 07:02 UTC
Labels: bug, parser
