### ISSUE TITLE
Undefined short options are misinterpreted as positional parameter

### ISSUE THREAD

**Issue by giaco777** [remkop/picocli#149] opened 2017-07-17 14:49 UTC
I use picocli and entered an undefined short option like e.g. '-x' on the command line as the first argument 
in the list like so:

<command> -x -v -g <name> abc def

This short option is not defined in the @Options/@parameter definition. When running, it confused the interpreter such, that none of the following command line arguments is parsed correctly anymore. No UnmatchedArgumentException is thrown!

I guess, I found the reason. In line 1330 of CommandLine.java there is a check of the length of the argument:

  else if (arg.length() > 2 && arg.startsWith("-")) { 

I my case the arg length is 2 and therefore it is not recognized as a short option. As a consequence the positional parameter processing is entered.

I changed the line such:

  else if (arg.length() >= 2 && arg.startsWith("-")) {

and now it seems to work properly

**Comment by remkop** [comment] 2017-07-18 10:29
Thanks for reporting this!

The current behavior is by design, but I am open to improvements.

My thinking was that when an argument is encountered which cannot be recognized as an option, to interpret that argument as a positional parameter.  Currently picocli follows [POSIX Guideline 9](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) that says all options should come before positional parameters. This means that once `-x` is interpreted as a positional parameter, all remaining arguments are **also** interpreted as positional parameters. 

_First improvement:_
I am planning to support [mixing options with positional parameters](https://github.com/remkop/picocli/issues/130). After this change, **only -x** will be interpreted as a positional parameter, -v and -g (when defined with `@Option`) will be recognized as options, and "abc" and "def" would be recognized as additional positional parameters.

_Further improvements:_
If I understand correctly you want picocli to throw an UnmatchedArgumentException if an argument starting with a hyphen (`-`) cannot be mapped to any of the `@Option` fields.

I don't want to hard-code this. Currently picocli accepts any value as a positional parameter. (It does perform type conversion, but after that there is no validation.)  An additional thing to bear in mind is that options can have any prefix, they don't need to start with a hypen. Picocli also supports options like `/H` `/F` etc., or even options without any prefix character.

A generic way to deal with the above requirements would be to allow some customizable validation on positional parameters. Still thinking about how to implement this... 

The application could also implement this easily with something like: `if (command.positionalParams[0].startsWith("-")) { throw new UnmatchedArgumentException(command.positionalParams[0]); }`. 
Picocli would need to offer a significanty shorter alternative or there is not much value...

**Comment by giaco777** [comment] 2017-07-19 15:30
Hi Remko,

 

thanks for reasoning about my input. You wrote:

 



Gesendet: Dienstag, 18. Juli 2017 um 12:29 Uhr
Von: "Remko Popma" <notifications@github.com>
An: remkop/picocli <picocli@noreply.github.com>
Cc: giaco777 <giaco777@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [remkop/picocli] Undefined short options are misinterpreted as positional parameter (#149)


Thanks for reporting this!

The current behavior is by design, but I am open to improvements.

My thinking was that when an argument is encountered which cannot be recognized as an option, to interpret that argument as a positional parameter. Currently picocli follows POSIX Guideline 9 that says all options should come before positional parameters. This means that once -x is interpreted as a positional parameter, all remaining arguments are also interpreted as positional parameters.

First improvement:
I am planning to support mixing options with positional parameters. After this change, only -x will be interpreted as a positional parameter, -v and -g (when defined with @Option) will be recognized as options, and "abc" and "def" would be recognized as additional positional parameters.

Further improvements:
If I understand correctly you want picocli to throw an UnmatchedArgumentException if an argument starting with a hyphen (-) cannot be mapped to any of the @Option fields.

Yes, this was my understanding of this exception. Why should a single character option like -x be interpreted as a positional parameter, whereas a multi-character option like -xyz not? Remember the query for the length of the option: 'else if (arg.length() > 2 && arg.startsWith("-")) {processClusteredShortOptions(required, initialized, arg, args);}'. To me this seems inconsistent.

I don't want to hard-code this. Currently picocli accepts any value as a positional parameter. (It does perform type conversion, but after that there is no validation.) An additional thing to bear in mind is that options can have any prefix, they don't need to start with a hypen. Picocli also supports options like /H /F etc., or even options without any prefix character.

A generic way to deal with the above requirements would be to allow some customizable validation on positional parameters. Still thinking about how to implement this...

The application could also implement this easily with something like: if (command.positionalParams[0].startsWith("-")) { throw new UnmatchedArgumentException(command.positionalParams[0]); }.

Ok, I can do it like this.


Picocli would need to offer a significanty shorter alternative or there is not much value...

**Comment by remkop** [comment] 2017-08-13 08:48
To follow up on this, I believe #158 will improve the situation.

#158 will add internal logging. As part of that work, I'm thinking to emit a WARN-level message (printed to System.err by default) when a command line argument starting with "-" cannot be assigned to any `@Option` and is assigned to a `@Parameters` field.

**Comment by remkop** [comment] 2017-08-23 12:46
Reading your comment again, I agree with what you are saying:

> Yes, this was my understanding of this exception. Why should a single character option like -x be interpreted as a positional parameter, whereas a multi-character option like -xyz not? Remember the query for the length of the option: 'else if (arg.length() > 2 && arg.startsWith("-")) {processClusteredShortOptions(required, initialized, arg, args);}'. To me this seems inconsistent.

You are correct, unknown single-char options are treated as positional params, while unknown multi-char options result in an UnmatchedArgumentException. This is inconsistent. 

For background, `processClusteredShortOptions` is trying to parse a cluster of one-character options, for example like `jar -xvf file.jar`. My intention was to only throw an UnmatchedArgException when such a cluster was partially, but not fully, processed, like for example `jar -xvHHHH file` (where -x and -v are valid options but -H is an unknown option). A multi-character option that could not be parsed as an option at all (not even partially) should have been treated as a positional parameter. This is a bug.

I originally thought that it would be sufficient to emit a WARN-level message "Unknown option -x", but still process that argument and the remainder as positional parameters, but I can see how this may be unsatisfactory.

I am now considering introducing a "strict mode" where arguments that "look like" an option but don't match any of the defined options would cause an UnmatchedArgumentException. In your example, -x looks like an option because it starts with a '-'. 

What I haven't figured out yet is how to do this while at the same time allowing any option prefix, because picocli also allows options starting with '/' or any character (there are no restrictions on the option prefix).

**Comment by remkop** [comment] 2017-08-25 11:47
Thinking about this more, I now think the strict mode should be the default. Arguments that "resemble" an option but cannot be matched with the defined options should cause an UnmatchedArgumentException. Arguments that do not resemble an option should be added to the positional arguments.

"Resemblance" can be defined as shared prefix: if an argument has one or more prefix characters in common with 9 out of 10 defined options, we decide it resembles an option and it is treated as an unmatched argument. 

We also consider the length of the shared prefix: so if known options are /a, /b, /c and --ccc, then argument --cc is still considered to resemble an option, since it has 4 matching prefix chars out of 4 option names.

**Comment by remkop** [comment] 2017-08-25 12:14
```
Index: src/main/java/picocli/CommandLine.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/picocli/CommandLine.java	(revision )
+++ src/main/java/picocli/CommandLine.java	(revision )
@@ -1587,6 +1587,8 @@
                 // We take this to mean that the remainder are positional arguments
                 else {
                     args.push(arg);
+                    if (tracer.isDebug()) {tracer.debug("Could not find option '%s', deciding whether to treat as unmatched option or positional parameter...%n", arg);}
+                    if (resemblesOption(arg)) { handleUnmatchedArguments(args.pop()); continue; } // #149
                     if (tracer.isDebug()) {tracer.debug("No option named '%s' found. Processing remainder as positional parameters%n", arg);}
                     processPositionalParameters(required, args);
                     return;
@@ -1602,6 +1604,18 @@
             };
         }
 
+        private boolean resemblesOption(String arg) {
+            int count = 0;
+            for (String optionName : optionName2Field.keySet()) {
+                for (int i = 0; i < arg.length(); i++) {
+                    if (optionName.length() > i && arg.charAt(i) == optionName.charAt(i)) { count++; } else { break; }
+                }
+            }
+            boolean result = count > 0 && count * 10 >= optionName2Field.size() * 9; // at least one prefix char in common with 9 out of 10 options
+            if (tracer.isDebug()) {tracer.debug("%s %s an option: %d matching prefix chars out of %d option names%n", arg, (result ? "resembles" : "doesn't resemble"), count, optionName2Field.size());}
+            return result;
+        }
+        private void handleUnmatchedArguments(String arg) {Stack<String> args = new Stack<String>(); args.add(arg); handleUnmatchedArguments(args);}
         private void handleUnmatchedArguments(Stack<String> args) {
             if (!isUnmatchedArgumentsAllowed()) { throw new UnmatchedArgumentException(args); }
             while (!args.isEmpty()) { unmatchedArguments.add(args.pop()); } // addAll would give args in reverse order
@@ -1695,10 +1709,16 @@
                     // We get here when the remainder of the cluster group is neither an option,
                     // nor a parameter that the last option could consume.
                     if (arg.endsWith(cluster)) {
-                        // remainder was part of a clustered group that could not be completely parsed
                         args.push(paramAttachedToOption ? prefix + cluster : cluster);
+                        if (args.peek().equals(arg)) { // #149 be consistent between unmatched short and long options
+                            if (tracer.isDebug()) {tracer.debug("Could not match any short options in %s, deciding whether to treat as unmatched option or positional parameter...%n", arg);}
+                            if (resemblesOption(arg)) { handleUnmatchedArguments(args.pop()); return; } // #149
+                            processPositionalParameters(required, args);
+                            return;
+                        }
+                        // remainder was part of a clustered group that could not be completely parsed
                         if (tracer.isDebug()) {tracer.debug("No option found for %s in %s%n", cluster, arg);}
-                        handleUnmatchedArguments(args);
+                        handleUnmatchedArguments(args.pop());
                     } else {
                         args.push(cluster);
                         if (tracer.isDebug()) {tracer.debug("%s is not an option parameter for %s%n", cluster, arg);}
```

**Comment by remkop** [comment] 2017-08-25 12:16
```
    @Test
    public void test149UnmatchedShortOptionsAreMisinterpretedAsOperands() {
        class App {
            @Option(names = "-a") String first;
            @Option(names = "-b") String second;
            @Option(names = {"-c", "--ccc"}) String third;
            @Parameters String[] positional;
        }
        //System.setProperty("picocli.trace", "DEBUG");
        try {
            CommandLine.populateCommand(new App(), "-xx", "-a");
            fail("UnmatchedArgumentException expected for -xx");
        } catch (UnmatchedArgumentException ex) {
            assertEquals("Unmatched arguments [-xx, -a]", ex.getMessage());
        }
        try {
            CommandLine.populateCommand(new App(), "-x", "-a");
            fail("UnmatchedArgumentException expected for -x");
        } catch (UnmatchedArgumentException ex) {
            assertEquals("Unmatched arguments [-x, -a]", ex.getMessage());
        }
        try {
            CommandLine.populateCommand(new App(), "--x", "-a");
            fail("UnmatchedArgumentException expected for --x");
        } catch (UnmatchedArgumentException ex) {
            assertEquals("Unmatched arguments [--x, -a]", ex.getMessage());
        }
    }
    @Test
    public void test149NonOptionArgsShouldBeTreatedAsOperands() {
        class App {
            @Option(names = "/a") String first;
            @Option(names = "/b") String second;
            @Option(names = {"/c", "--ccc"}) String third;
            @Parameters String[] positional;
        }
        //System.setProperty("picocli.trace", "DEBUG");
        App app = CommandLine.populateCommand(new App(), "-yy", "-a");
        assertArrayEquals(new String[] {"-yy", "-a"}, app.positional);

        app = CommandLine.populateCommand(new App(), "-y", "-a");
        assertArrayEquals(new String[] {"-y", "-a"}, app.positional);

        app = CommandLine.populateCommand(new App(), "--y", "-a");
        assertArrayEquals(new String[] {"--y", "-a"}, app.positional);
    }
    @Test
    public void test149LongMatchWeighsWhenDeterminingOptionResemblance() {
        class App {
            @Option(names = "/a") String first;
            @Option(names = "/b") String second;
            @Option(names = {"/c", "--ccc"}) String third;
            @Parameters String[] positional;
        }
        //System.setProperty("picocli.trace", "DEBUG");
        try {
            CommandLine.populateCommand(new App(), "--ccd", "-a");
            fail("UnmatchedArgumentException expected for --x");
        } catch (UnmatchedArgumentException ex) {
            assertEquals("Unmatched arguments [--ccd, -a]", ex.getMessage());
        }
    }
    @Test
    public void test149OnlyUnmatchedOptionStoredOthersParsed() throws Exception {
        class App {
            @Option(names = "-a") String first;
            @Option(names = "-b") String second;
            @Option(names = {"-c", "--ccc"}) String third;
            @Parameters String[] positional;
        }
        //System.setProperty("picocli.trace", "DEBUG");
        PrintStream originalErr = System.err;
        ByteArrayOutputStream baos = new ByteArrayOutputStream(2500);
        System.setErr(new PrintStream(baos));

        CommandLine cmd = new CommandLine(new App()).setUnmatchedArgumentsAllowed(true).parse("-yy", "-a=A").get(0);
        assertEquals(Arrays.asList("-yy"), cmd.getUnmatchedArguments());
        assertEquals("A", ((App) cmd.getCommand()).first);

        cmd = new CommandLine(new App()).setUnmatchedArgumentsAllowed(true).parse("-y", "-b=B").get(0);
        assertEquals(Arrays.asList("-y"), cmd.getUnmatchedArguments());
        assertEquals("B", ((App) cmd.getCommand()).second);

        cmd = new CommandLine(new App()).setUnmatchedArgumentsAllowed(true).parse("--y", "-c=C").get(0);
        assertEquals(Arrays.asList("--y"), cmd.getUnmatchedArguments());
        assertEquals("C", ((App) cmd.getCommand()).third);

        String expected = String.format("" +
                        "[picocli WARN] Unmatched arguments: [-yy]%n" +
                        "[picocli WARN] Unmatched arguments: [-y]%n" +
                        "[picocli WARN] Unmatched arguments: [--y]%n");
        String actual = new String(baos.toByteArray(), "UTF8");
        assertEquals(expected, actual);
    }
```

**Closed** 2017-08-26 13:39 UTC
