### ISSUE TITLE
Localisation of phrase "Default"

### ISSUE THREAD

**Issue by deining** [remkop/picocli#605] opened 2019-01-14 16:07 UTC
I have a simple command with showDefaultValues=true:

```
Usage: parent [-m=<number>]
  -m, --minimum=<number>     Default: 3
```

Is there a simple way to localize the phrase 'Default' via an entry in the resource bundle so that  the output with German locale looks like this?

```
Usage: parent [-m=<number>]
  -m, --minimum=<number>     Voreinstellung: 3
```

Thanks for your support.

**Comment by remkop** [comment] 2019-01-15 07:08
I confirmed this works:

```java
package test;

import static org.junit.Assert.*;
import org.junit.Test;
import picocli.CommandLine;
import picocli.CommandLine.Command;

import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Vector;

public class I18nTest {

    @Test
    public void testI18nDemo() {

        CommandLine commandLine = new CommandLine(new I18nDemo());

        String actual = commandLine.getUsageMessage();
        String expected = String.format("" +
                "Usage: i18n [-x=<x>] [-y=<y>]%n" +
                "bundle text%n" +
                "  -x=<x>    日本語 34 for x%n" +
                "  -y=<y>    日本語 4444 for y%n");

        assertEquals(expected, actual);
    }

    @Command(name="i18n", resourceBundle = "test.I18nTest$MyBundle")
    static class I18nDemo {
        @CommandLine.Option(names = "-x", defaultValue = "34") int x;
        @CommandLine.Option(names = "-y") int y = 4444;
    }


    public static class MyBundle extends ResourceBundle {
        Map<String, String> map = new HashMap<String, String>();

        public MyBundle() {
            map.put("usage.description",  "bundle text");
            map.put("x",  "日本語 ${DEFAULT-VALUE} for x");
            map.put("y",  "日本語 ${DEFAULT-VALUE} for y");
        }

        protected Object handleGetObject(String s) {
            return map.get(s);
        }

        public Enumeration<String> getKeys() {
            return new Vector<String>(map.keySet()).elements();
        }
    }
}

```

**Comment by deining** [comment] 2019-01-15 09:38
Yes, I can confirm that this works, and this is a valid solution for sure.
Since this soluton is a bit more verbose than simply using 'showDefaultValues = true' I'm asking myself whether it would make sense to provide the opportunity to localize the string resource 'Default' used in that context. Reasonable proposal or feature creep?

Everything looks great now in my use case, except for one minor issue. I'm using:

```
@Command(subcommands = { CommandLine.HelpCommand.class, xx.class })
    static class Parent implements Runnable { ...
```

Requesting help for the parent command results in

```
Usage: Parent [-hvV] [COMMAND]
Description of parent command
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  xx             Description of subcommand
  help           Displays help information about the specified command
```

Is there any easy way to localize the description for the 'help' subcommand ('_Displays help information about the specified command_')? Thanks for you answer!

**Comment by remkop** [comment] 2019-01-15 11:39
I think you can override by providing entries in your resource bundle:

```
# Example bundle for the “parent” command 
parent.help.usage.description=my description 
```

**Comment by deining** [comment] 2019-01-15 12:37
No, that didn't do the trick for me.

**Comment by remkop** [comment] 2019-01-15 12:58
Ok, I’ll try to test this tomorrow. Is the spelling of the key correct? Should it be capitalized “Parent” for your application?

**Comment by remkop** [comment] 2019-01-15 23:50
**Localizing the built-in help subcommand**

I found it. The resource bundle keys for the built-in `help` command are:

```
# for a specific subcommand, e.g., `parent help`
parent.help.usage.header=Dit is de `help` subcommand van de `parent` command
parent.help.help=Dit beschrijft de --help option van de `help` subcommand van de `parent` command
parent.help.version=Dit beschrijft de --version option van de `help` subcommand van de `parent` command

# or have one global entry for the `help` subcommand
help.usage.header=Dit is de `help` subcommand
help.help=Dit beschrijft de --help option van de `help` subcommand
help.version=Dit beschrijft de --version option van de `help` subcommand
```

**Comment by remkop** [comment] 2019-01-15 23:56
About using `showDefaultValues = true` vs `${DEFAULT-VALUE}`: I recommend using the variable since it gives the most flexibility and easily lends itself to internationalization and localization. 

Going forward I plan to [add more variables](https://github.com/remkop/picocli/issues/526) like this. (If I had thought of the variables first I would not have provided the  `showDefaultValues = true` mechanism. But hindsight is perfect, as they say...) :-)

**Comment by remkop** [comment] 2019-01-16 00:39
I will update the [Internationalization](https://picocli.info/#_internationalization) section of the user manual to clarify:

* How to localize descriptions for the built-in `help` subcommand and its options 
* That the `showDefaultValues=true` directive doesn’t lend itself to easy localization and that the recommended alternative is to embed the `${DEFAULT-VALUE}` variable in the localized text in the resource bundle messages

**Comment by remkop** [comment] 2019-01-16 07:37
That would be great, thank you!
Agreed on both proposals.

**Comment by remkop** [comment] 2019-01-19 10:33
@deining, how is it going? Let me know if you need any help.

**Comment by remkop** [comment] 2019-01-19 11:42
I added an extra test and update the Internationalization section of the user manual.

**Comment by deining** [comment] 2019-01-19 16:44
Thanks for your efforts, everything is fine for me now. 
I try to add a fully working example soon.

**Comment by remkop** [comment] 2019-02-01 10:03
If you don't mind I will close this ticket.
Additional PRs are always welcome! :-)

**Closed by remkop** 2019-02-01 10:03 UTC
Labels: doc, question
