### ISSUE TITLE
Codegen fails when command contains field with argGroup annotation (4.0.1)

### ISSUE THREAD

**Issue by eomeara** [remkop/picocli#777] opened 2019-07-30 13:41 UTC
Sample argGroup code in documentation causes codegen to fail during gradle build. 
Also don't know why warning is present.
Sample project attached.

**build.gradle.kts**
```kotlin
plugins {
    `java-library`
}

repositories {
    mavenLocal()
    maven {
        url = uri("http://repo.maven.apache.org/maven2")
    }
}

dependencies {
    implementation("info.picocli:picocli-spring-boot-starter:4.0.1")
    annotationProcessor("info.picocli:picocli-codegen:4.0.1")
}
```

**MutuallyExclusiveOptionsDemo.java**
```java
package bug.codegen.ArgGroup;

import picocli.CommandLine.*;

@Command(name = "exclusivedemo")
public class MutuallyExclusiveOptionsDemo {

    @ArgGroup(exclusive = true, multiplicity = "1")
    Exclusive exclusive;

    static class Exclusive {
        @Option(names = "-a", required = true) int a;
        @Option(names = "-b", required = true) int b;
        @Option(names = "-c", required = true) int c;
    }
}
```
**Gradle console output**
```text
.\gradlew clean build

> Task :compileJava FAILED
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
C:\Users\auser\Documents\args-bug\src\main\java\bug\codegen\ArgGroup\MutuallyExclusiveOptionsDemo.java:9: error: @ArgGroups must be enclosed in a @Command or @ArgGroup-annotated element, but was bug.codegen.ArgGroup.MutuallyExclusiveOptionsDemo: MutuallyExclusiveOptionsDemo
    Exclusive exclusive;
              ^
Note: ReflectConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/reflect-config.json
Note: ResourceConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/resource-config.json
Note: ProxyConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/proxy-config.json
1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```
[args-bug.zip](https://github.com/remkop/picocli/files/3446878/args-bug.zip)

**Comment by remkop** [comment] 2019-07-30 14:05
Thanks for reporting this!
This looks like a bug in the annotation processor. I’ll take a look.

**Comment by remkop** [comment] 2019-08-01 05:51
I was able to reproduce the problem. There are several issues with argument groups in the annotation processor. I am looking at how to address this.

About the warning: The picocli annotation processor is compiled with Java 6, and by default has a supported source version of RELEASE_6. Looking at [this StackOverflow](https://stackoverflow.com/questions/23044511/supported-source-version-release-6-from-annotation-processor-org-eclipse-persist) question, there may not much that can be done about it. I agree this is annoying.

**Comment by remkop** [comment] 2019-08-04 22:16
It took a while, but I pushed a fix for this issue to master.
It would be great if you can confirm.

I will add some more tests and hope to do a 4.0.2 release with this fix later this week.

**Closed** 2019-08-06 11:27 UTC
Labels: bug, codegen

**Comment by remkop** [comment] 2019-08-06 11:31
Fixed in master.
@eomeara  It would be great if you could confirm. The easiest way to do this is to check out the project in git, then run `gradlew publishToMavenLocal` on the command line. (Or `gradlew  -x check publishToMavenLocal` to skip the tests.)

After that you can use the `picocli-4.0.2-SNAPSHOT` dependency in your project.

**Comment by eomeara** [comment] 2019-08-06 13:13
Will try to check this evening. Was on bank holiday weekend Saturday to Monday.

**Comment by eomeara** [comment] 2019-08-07 09:52
My build now succeeds and all tests pass. In future I intend to move my code to GraalVM, though not yet.
Using the annotation processor is my first step.
P.S. Thanks for a great library.

**Comment by remkop** [comment] 2019-08-07 10:14
Thank you for the confirmation!
