### ISSUE TITLE
How to suggest options and sub-command at the same time?

### ISSUE THREAD

**Issue by zlxie** [remkop/picocli#827] opened 2019-09-27 08:19 UTC
Hi, 
I have command line like "icmd -v -h -o sub1 sub2", and sub1 and sub2 are sub commands. I tried to use picocli(version is 4.0.4) to generate auto completion script, and it only works as below:  
->icmd TAB TAB
sub1 sub2
->icmd -TAB
-v -h -o
But actually I want to show all options and sub-command as below. How should I do? Thanks.
->icmd <tab>
-v -h -o sub1 sub2

**Comment by remkop** [comment] 2019-09-27 08:45
Hi, that was done to allow default bash completions.
This can get quite complex. See the discussion in https://github.com/remkop/picocli/issues/461

My understanding is that the current picocli completion behaviour is consistent with [bash-completion](https://github.com/scop/bash-completion). I am open to improvements though.

**Comment by DaitariJena1505** [comment] 2019-11-18 08:57
Hi, 

I have sping boot + picocli application. I want to implement TAB auto completion feature to show the  params and options in my application. Could you please help me how to do that. I am using  picocli-3.8.2.jar.

Your help is most appriciated.

Thanks
Daitari Jena

**Comment by remkop** [comment] 2019-11-18 10:14
Hi @DaitariJena1505, I would always recommend upgrading to the latest version (picocli 4.0.4). Is there anything preventing you from upgrading?

About your question, have you had a chance to read the [autocompletion user manual](https://picocli.info/autocomplete.html)?

**Comment by DaitariJena1505** [comment] 2019-11-18 10:56
No the problem is when i am executing the command  : java -cp "picocli-3.8.2.jar:my.jar" picocli.AutoComplete -n login /BOOT-INF/classes/com.xyz.123.cli.command.LoginCommand , it is showing the error 

java.lang.ClassNotFoundException:  /BOOT-INF/classes/com.xyz.123.cli.command.LoginCommand

**Comment by remkop** [comment] 2019-11-18 11:18
You need to specify a fully qualified class name. Have you tried without the “ /BOOT-INF/classes/” prefix?

```
java -cp "picocli-3.8.2.jar:my.jar" picocli.AutoComplete -n login com.xyz.123.cli.command.LoginCommand
```

**Comment by DaitariJena1505** [comment] 2019-11-19 05:53
Yes, i have tried that one also but same issue.

**Comment by remkop** [comment] 2019-11-19 06:05
Surely it cannot be the same; at least the error message should be different...

Is there any way for me to try to reproduce the issue? Could you create a test project?

**Comment by remkop** [comment] 2019-11-19 07:01
Also, can you post the result of `jar -tvf myjar.jar`? I would like to see where the `com.xyz.123.cli.command.LoginCommand` class is located inside the jar.

**Comment by DaitariJena1505** [comment] 2019-11-19 07:32
5372 Mon Nov 18 12:53:26 GMT 2019 
BOOT-INF/classes/com/xyz/123/cli/command/LoginCommand.class

**Comment by remkop** [comment] 2019-11-19 07:58
Ok that’s the problem. That’s a [Spring executable jar](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-executable-jar-format.html), not a normal jar. 

Your LoginCommand class is not visible on the classpath. 

Can you extract your class and run the autocompletion generator again?

**Comment by DaitariJena1505** [comment] 2019-11-19 08:29
After extraction, where i will put the class ?

**Comment by remkop** [comment] 2019-11-19 08:39
Just any directory is fine. For example:

```
.
├── classes
│   └── com
│       └── xyz
│           └── 123
│               └── cli
│                   └── command
│                       └── LoginCommand.class
└──  picocli-4.0.4.jar
```

Then, run:

```
java -cp "picocli-4.0.4.jar:classes" picocli.AutoComplete -n login \ 
  com.xyz.123.cli.command.LoginCommand
```

**Comment by remkop** [comment] 2019-11-19 08:44
@DaitariJena1505 By the way, see [AutoCompletion distribution](https://picocli.info/autocomplete.html#_distribution) for an alternative way to distribute autocompletion scripts with your application: the idea is to give your top-level command a subcommand that end-users can use to generate and install the autocompletion script. (Just an idea.)

**Comment by DaitariJena1505** [comment] 2019-11-19 08:49
Sorry to ask again, after extract the LoginCommand.class i have to create folder structure as above and re-build the jar again ?

**Comment by remkop** [comment] 2019-11-19 08:57
After you have run `java -cp "picocli-4.0.4.jar:classes" picocli.AutoComplete -n login com.xyz.123.cli.command.LoginCommand` you should have a completion script that you can distribute with your application. If the old (Spring executable) jar `myjar.jar` works for you, then just keep using that, I guess. I am not very familiar with Spring executable jars.

**Comment by DaitariJena1505** [comment] 2019-11-20 05:16
Do you have any sample project for Auto completion ? If you can share it would be a great help for me.

**Comment by DaitariJena1505** [comment] 2019-11-20 06:09
After generating the completion script, how will i use that script ?

**Comment by remkop** [comment] 2019-11-20 06:54
@DaitariJena1505 You [install it](https://picocli.info/autocomplete.html#_install_completion_script) by sourcing the script. Then you can use tab completion for that command in that shell session.

**Comment by DaitariJena1505** [comment] 2019-11-20 08:55
You mean to say i have to run ->  source login_completion
The  run the jar -> java -jar myjar.jar 
After that project will ask for login using login command that time tab completion will work ?

**Comment by remkop** [comment] 2019-11-20 11:43
No, if you run `java -jar x.jar` it won’t work. 
Please look at the [documentation](https://picocli.info/autocomplete.html#_quick_start_tutorial): you need to create a named command in Unix. You can use an alias or a script. 

If your command is `login`, create a script with that name that invokes `java -jar x.jar` or something to invoke your java program. This script then becomes the command that end users use to run your program. 

When you create an autocompletion script you need to specify the command name. This command name (basically your script) is associated with a specific command and only when users enter that command it will trigger the bash completion for that command.

**Comment by DaitariJena1505** [comment] 2019-11-21 05:54
Hi,
Just want to clarify the below points.

Step 1 : alias login='java -cp "picocli-3.8.2.jar:myproject.jar" com.test.LoginCommand'

Step 2 : java -cp "picocli-3.8.2.jar:myproject.jar" picocli.AutoComplete -n login com.xyz.123.cli.command.LoginCommand

Step 3: Auto Completion script got created with the name -  login_completion

Step 4 : i have write a script where i have to write the below code.

echo "alias login='java -cp \"picocli-1.0.0.jar;myproject.jar\" com.test.LoginCommand'" >> ~/.bashrc
echo ". ogin_completion" >> ~/.bashrc

Could you please confirm if the above steps are correct for auto completion.

**Comment by remkop** [comment] 2019-11-21 10:22
Looks more or less okay. Some details: 

Use full path to the jars in the alias: if the user invokes the `login` command, the shell will try to run `java -cp "picocli-3.8.2.jar:myproject.jar" com.test.LoginCommand`. This may succeed, if those two jars exist in the current directory. It may be better to specify the full path to these jar files in the alias.

In the alias, the class name is `com.test.LoginCommand`, but your completion script is created for `com.xyz.123.cli.command.LoginCommand`. Should these not be the same? (This may not be a problem if these have the same options and positional parameters).

`echo ". ogin_completion" >> ~/.bashrc` 
should be
`echo ". login_completion" >> ~/.bashrc`

**Comment by remkop** [comment] 2020-01-09 06:47
Closing for now: current picocli completion behaviour is consistent with bash-completion.

**Closed by remkop** 2020-01-09 06:47 UTC
Labels: auto-completion, wontfix
