### ISSUE TITLE
Can't find ResourceBundle with JPMS

### ISSUE THREAD

**Issue by tasogare3710** [remkop/picocli#1420] opened 2021-08-30 14:31 UTC
ResourceBundle fails to load if the ResourceBundle is specified using the resourceBundle element of the CommandLine.Command annotation.

info.picocli/CommandLine$Model$Messages#createBundle is calling ResourceBundle#getBundle(String), so it seems to be looking for ResourceBundle from info.picocli module. Is there a way to specify the module in which the ResourceBundle or to use the ResourceBundleProvider?

**Comment by remkop** [comment] 2021-08-31 01:32
Thank you for raising this!

Looking at the javadoc for [Resource Bundles in Named Modules](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html#bundleprovider), and [ResourceBundleProvider](https://docs.oracle.com/javase/9/docs/api/java/util/spi/ResourceBundleProvider.html), no, this is currently not yet supported in picocli as of version 4.6.1.

I am not opposed to adding support for this. One thing to note is that in order to continue to only require Java 5 or higher at runtime, adding support for resource bundles in modules will require the use of reflection. It is likely that only the [`CommandLine.Model.Messages`](https://picocli.info/apidocs/picocli/CommandLine.Model.Messages.html) class needs to be modified, but I have not looked at the details of what the implementation would look like.

A potential issue is that picocli currently only requires Java 8 or higher to build the project. 
So how do we test this functionality?

When running [in continuous integration environments](https://github.com/remkop/picocli/blob/master/.travis.yml), picocli is built and all tests are executed on Java versions 8-16.
One idea is to have some tests that are only executed when running on Java 9 or higher.
Also, we could create a small pre-built picocli-based application that is a JPMS module, include the binary JAR of that application to the resources of the picocli project, and reference this application from the test (again, only when running on Java 9 or higher).

Do you think you will be able to provide a pull request for this?

**Comment by tasogare3710** [comment] 2021-08-31 11:15
>Do you think you will be able to provide a pull request for this?

I'm so sorry, but I not know picocli inside out to send a pull request.

>A potential issue is that picocli currently only requires Java 8 or higher to build the project.
So how do we test this functionality?

I'm not sure if this will work with picocli, but how about using a [multi release jar files](https://docs.oracle.com/javase/10/docs/specs/jar/jar.html#multi-release-jar-files) and including picocli for java8 and picocli for java9 and higher in single jar file?

**Comment by tasogare3710** [comment] 2021-08-31 12:29
This is the smallest [gradle project](https://github.com/remkop/picocli/files/7083791/picocli_i18n_test.zip) that can reproduce this issue.


unzip, cd and run:

```
gradlew run
```

1. This will fail to run.
2. Uncomment line 17 of app\build.gradle and comment out lines 18 and 19 to successfully run.

**Comment by remkop** [comment] 2021-09-02 05:20
Thank you for providing the sample project.

> I'm so sorry, but I not know picocli inside out to send a pull request.

Understood, no problem.
I am extremely pressed for time and I don't see myself working on this issue in the near future.

Let's leave this ticket open for someone who is willing to work on it.

**Comment by tasogare3710** [comment] 2021-09-02 09:59
Of course. no problem too.

Thank you.

**Comment by aalmiray** [comment] 2023-02-10 17:53
Interested in seeing this issue moving forward. How can we keep backward compatibility while supporting Java 9+ and modules?

**Comment by tasogare3710** [comment] 2023-02-14 09:28
JPMS is not backward compatibility. upgrade path called --illegal-access option was removed in java17, but you can still use multi-release-jar.
And next LTS will be released this September.

https://openjdk.org/jeps/238
https://openjdk.org/jeps/403

**Comment by aalmiray** [comment] 2023-02-14 09:31
Might be much to ask to use MR-JARs as most of picocli is implemented as an annotation with embedded types. For this to work the class responsible for loading resources would have to move to a top level class, then a Java9+ compatible implementation may be placed in `/META-INF/versions/9`.

**Comment by tasogare3710** [comment] 2023-02-14 10:41
Mhh, divide into smaller milestones step by step.

**Comment by remkop** [comment] 2023-02-14 11:10
I’m assuming that the programmatic API [`CommandLine.setResourceBundle`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.html#setResourceBundle(java.util.ResourceBundle)) works correctly with modular applications, is that right?

**Comment by aalmiray** [comment] 2023-02-14 13:43
Yes. Using the programmatic API works with modules.

**Comment by aalmiray** [comment] 2023-02-14 14:27
FWIW These are the changes I had to make to Jarviz to turn it into a full modular CLI https://github.com/kordamp/jarviz/commit/fd21b1f4ee5e31d8a9d5dcd89cf0527bc94bf377

**Comment by remkop** [comment] 2023-02-15 01:56
My initial thoughts on solving this would be:
* First, we should document that for modular CLI applications, when using picocli 4.7.1 or earlier, there is a problem with the annotations and they need to call the programmatic API [`CommandLine.setResourceBundle`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.html#setResourceBundle(java.util.ResourceBundle)). This needs to be mentioned in the User Manual and in the javadoc for resource-bundle related methods and annotation elements.
* the fix for this problem with the [`@Command(resourceBundle="xxx")`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Command.html#resourceBundle()) annotation may be relatively straight-forward: One idea is to use reflection to call  the [`ResourceBundle.getBundle`](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.lang.Module-) method with the [`Module`](https://docs.oracle.com/javase/9/docs/api/java/lang/Module.html) of the user object of the command. The "user object" here is the class that was annotated with `@Command`. We can obtain the user object's `Module` via [Class.getModule](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#getModule--) by using reflection.

Thoughts?

-----

_Note to self: relevant documentation below:_
 
* https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html
* https://docs.oracle.com/javase/9/docs/api/java/util/spi/ResourceBundleProvider.html

> ### Resource Bundles in Named Modules
> When resource bundles are deployed in named modules, the following module-specific requirements and restrictions are applied.
> * Code in a named module that calls [getBundle(String, Locale)](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.util.Locale-) will locate resource bundles in the caller's module (_caller module_).
> * If resource bundles are deployed in named modules separate from the caller module, those resource bundles need to be loaded from service providers of [ResourceBundleProvider](https://docs.oracle.com/javase/9/docs/api/java/util/spi/ResourceBundleProvider.html). The caller module must declare `"uses"` and the service interface name is the concatenation of the package name of the base name, string ".spi.", the simple class name of the base name, and the string "Provider". The _bundle provider modules_ containing resource bundles must declare `"provides"` with the service interface name and its implementation class name. For example, if the base name is "com.example.app.MyResources", the caller module must declare "uses com.example.app.spi.MyResourcesProvider;" and a module containing resource bundles must declare "provides com.example.app.spi.MyResourcesProvider with com.example.app.internal.MyResourcesProviderImpl;" where com.example.app.internal.MyResourcesProviderImpl is an implementation class of com.example.app.spi.MyResourcesProvider.
> * If you want to use non-standard formats in named modules, such as XML, [ResourceBundleProvider](https://docs.oracle.com/javase/9/docs/api/java/util/spi/ResourceBundleProvider.html) needs to be used.
> * The `getBundle` method with a `ClassLoader` may not be able to find resource bundles using the given `ClassLoader` in named modules. The [`getBundle`](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.lang.Module-) method with a [`Module`](https://docs.oracle.com/javase/9/docs/api/java/lang/Module.html) can be used, instead.
> * `ResourceBundle.Control` is not supported in named modules. If the `getBundle` method with a `ResourceBundle.Control` is called in a named module, the method will throw an `UnsupportedOperationException`. Any service providers of [ResourceBundleControlProvider](https://docs.oracle.com/javase/9/docs/api/java/util/spi/ResourceBundleControlProvider.html) are ignored in named modules.
> 
> 
> ### ResourceBundleProvider Service Providers
> The `getBundle` factory methods load service providers of [ResourceBundleProvider](https://docs.oracle.com/javase/9/docs/api/java/util/spi/ResourceBundleProvider.html), if available, using [ServiceLoader](https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html). The service type is designated by `<package name> + ".spi." + <simple name> + "Provider"`. For example, if the base name is `"com.example.app.MyResources"`, the service type is `com.example.app.spi.MyResourcesProvider`.
> In named modules, the loaded service providers for the given base name are used to load resource bundles. If no service provider is available, or if none of the service providers returns a resource bundle and the caller module doesn't have its own service provider, the `getBundle` factory method searches for resource bundles that are local in the caller module and that are visible to the class loader of the caller module. The resource bundle formats for local module searching are "java.class" and "java.properties".
>

**Comment by aalmiray** [comment] 2023-02-15 11:28
> My initial thoughts on solving this would be:
> 
>     * First, we should document that for modular CLI applications, when using picocli 4.7.1 or earlier, there is a problem with the annotations and they need to call the programmatic API [`CommandLine.setResourceBundle`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.html#setResourceBundle(java.util.ResourceBundle)). This needs to be mentioned in the User Manual and in the javadoc for resource-bundle related methods and annotation elements.

👍 

>     * the fix for this problem with the [`@Command(resourceBundle="xxx")`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Command.html#resourceBundle()) annotation may be relatively straight-forward: One idea is to use reflection to call  the [`ResourceBundle.getBundle`](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.lang.Module-) method with the [`Module`](https://docs.oracle.com/javase/9/docs/api/java/lang/Module.html) of the user object of the command. The "user object" here is the class that was annotated with `@Command`. We can obtain the user object's `Module` via [Class.getModule](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#getModule--) by using reflection.

I suppose this will work as long as the module is open to `info.picocli` otherwise reflection will fail.

**Comment by remkop** [comment] 2023-02-15 11:51
> I suppose this will work as long as the module is open to `info.picocli` otherwise reflection will fail.

True; that bit is [already documented](https://picocli.info/#_module_configuration) .

**Comment by remkop** [comment] 2023-02-18 13:09
@aalmiray @tasogare3710 Good news:
it turns out that no changes to the picocli library are necessary; I was able to get it to work with picocli 4.7.1.

What is needed is:
* the resource bundle properties or class file must exist in the application jar at [the correct location](https://docs.oracle.com/javase/9/docs/api//java/lang/Module.html#getResourceAsStream-java.lang.String-)
* the `module-info.java` must use `opens yourpackage;` it **_must not use_** `opens yourpackage to info.picocli;`!

```java
module mymodule {
    requires info.picocli;

    // Open this package for reflection to external frameworks.
    opens mycommandpackage;

    // THE BELOW DOES NOT WORK! 
    // The below syntax results in MissingResourceException: Can't find bundle for base name XXX
    //    opens mycommandpackage to info.picocli;  // AVOID THIS
}
```

**Comment by aalmiray** [comment] 2023-02-18 16:26
Strange, as I do have an explicit opens to `picocli` and it works. See last line at https://github.com/kordamp/jarviz/blob/main/plugins/jarviz-cli/src/main/java/module-info.java

**Comment by remkop** [comment] 2023-02-18 19:59
@aalmiray I thought you got it to work by calling the programmatic API? (So you are calling `ResourceBundle.getBundle` in your own code.)

**Comment by aalmiray** [comment] 2023-02-18 20:20
That is correct. I'm using the programmatic API form within the same module.

**Comment by remkop** [comment] 2023-02-19 00:13
Yes, so calling the programmatic API always works regardless of module stuff.

What I am talking about is, in order to get the `@Command(resourceBundle = "something")` annotation to work, 
your `module-info.java` needs to use `opens X` instead of `opens X to info.picocli`.

@tasogare3710 can you try to see if that resolves the issue for you also?

**Comment by tasogare3710** [comment] 2023-02-19 16:06
@remkop `opens yourpackage` says that `yourpackage` allows reflection for all other modules. We need to do is to give `yourpackage` proper list of allowed reflection.

> The below syntax results in MissingResourceException: Can't find bundle for base name XXX

It looks like same as this issue.

**Comment by remkop** [comment] 2023-02-19 22:12
@tasogare3710 I tried the [example project you attached](https://github.com/remkop/picocli/files/7083791/picocli_i18n_test.zip) to this ticket, and if I change the `module-info.java` it works without any error.

```java
// picocli_i18n_test\app\src\main\java\module-info.java
module picotest {
    requires java.base;
    requires info.picocli;

    opens picotest;
}
```

The output:
```
C:\Users\remko\IdeaProjects\picocli_i18n_test>gradlew run    

> Task :app:run
false

BUILD SUCCESSFUL in 4s
```

I confirmed this works with either picocli 4.6.1 or 4.7.1.

I will update the documentation for [Module Configuration](https://picocli.info/#_module_configuration) accordingly.

**Comment by tasogare3710** [comment] 2023-02-20 17:38
>     opens picotest; // <--- this was missing

I'm sorry, my mistake. But that mistake not relevant this issue, so forget it.

- - -

> info.picocli/CommandLine$Model$Messages#createBundle is calling ResourceBundle#getBundle(String), so it seems to be looking for ResourceBundle from info.picocli module.

this direct cause of this isssue. This call is same as `getBundle(baseName, Locale.getDefault(), callerModule)`. callerModule is info.picocli.
Essentially, this problem stems from the fact that code snippets that should be executed in the codebase of app are being executed in the codebase of library.

It's strange it runs without problems if you use `opens picotest` and allow reflection on picotest in all modules.

**Comment by tasogare3710** [comment] 2023-02-20 18:57
In short, have to find ResourceBundle from picotest module, but `@Command` does not support JPMS, so finding for ResourceBundle from module self(info.picocli@4.7.1) belong to.

- It caused ResourceBundle#getBundleImpl(Module,Module,String,Locale,Control) cannot find both baseBundle and bundle, and throws MissingResourceException.
- ResourceBundle#getBundleImpl(Module,Module,String,Locale,Control) is called by ResourceBundle#getBundle(String).

**Comment by tasogare3710** [comment] 2023-02-20 21:33
It is because the caller of method is incorrect; there is a issue with the codebase that calls getBundle.

**Comment by remkop** [comment] 2023-02-21 02:26
@tasogare3710 I don't understand...
> It is because the caller of method is incorrect; there is a issue with the codebase that calls getBundle.

I believe I have evidence that disproves your hypothesis:
For example, the sample [test subproject](https://github.com/remkop/picocli/tree/main/picocli-tests-jpms-modules) has a test class called [ResourceBundleTest](https://github.com/remkop/picocli/blob/main/picocli-tests-jpms-modules/app-it/src/test/java/picocli/test_jpms/modular_app/it/ResourceBundleTest.java). This class does not use picocli (so has nothing to do with the `@Command` annotation), it simply tries to call `ResourceBundle.getBundle` from the `app-it` module for a resource bundle that lives in a different `app` module. 

This is the code for one of the tests, it does not use reflection and it clearly uses the correct `Module` to call `getBundle`:

```java
// this test lives in the app-it module
@Test
public void testLoadBundleModular() throws Exception {

    // the JpmsModularApp class lives in the app module
    Module module = JpmsModularApp.class.getModule(); // this is the app module

    // the picocli/test_jpms/modular_app/messages.properties file lives in the app module
    ResourceBundle bundle = ResourceBundle.getBundle("picocli.test_jpms.modular_app.messages", module);
    System.out.println(bundle);
    System.out.println(bundle.getString("usage.headerHeading"));
}
```

Now, this test _**only works**_ if the `module-info` for the `app` module has `opens picocli.test_jpms.modular_app;`.
It is the same with the other tests in the `ResourceBundleTest` class. 
All these ways of calling fail/succeed the same way:
* ResourceBundle.getBundle(String)
* ResourceBundle.getBundle(String, Locale)
* ResourceBundle.getBundle(String, Module)

So it seems to me that it is necessary to have `opens packageName` in the `module-info` of the module containing the resource bundle, to make _any_ variant of `ResourceBundle.getBundle` work.

Are you suggesting that there is a way to make `ResourceBundle.getBundle(String, Module)` (with the correct `Module` passed in) work, without having `opens packageName` in the `module-info` of the module that contains the resource bundle?
Can you provide a working example?

**Comment by tasogare3710** [comment] 2023-02-21 05:42
This is not my analysis but module mechanism. java8 and unconditionally open module do not protect a resource from this case. the MissingResourceException is caused by a security check failure in the open module. There seems to be a misunderstanding.

**Comment by tasogare3710** [comment] 2023-02-21 06:06
There also seems to be some misunderstanding about reflection: ResourceBundle uses reflection, and JLS also describes it as follows

https://docs.oracle.com/javase/specs/jls/se9/html/jls-7.html#jls-7.7.2
> It also grants reflective access to all types in the package, and all their members, for code in other modules.

**Comment by remkop** [comment] 2023-02-21 07:47
Sorry @tasogare3710 I don't understand your last few comments.

Here is my understanding:
You came to me with a problem (this ticket): 
> ResourceBundle fails to load if the ResourceBundle is specified using the resourceBundle element of the CommandLine.Command annotation.

I provided a solution. In fact, for practical purposes there are two solutions:
* use picocli's `CommandLine.setResourceBundle` programmatic API to bypass this problem
* put `opens packageName` in the `module-info` of the module that contains the resource bundle

I provided tests that show that this is actually an effective solution, and ResourceBundles are loaded correctly when this solution is applied.

After that, your replies are a bit confusing.  😅 
I get the impression that you don't like this solution to put `opens pn` in the `module-info`, for some reason.

This is your choice and totally fine of course, but from my point of view the problem is solved.
If you want further help, you need to be clear about your requirements: what exactly is unsatisfactory about this solution, and what kind of solution would meet your requirements?

**Comment by remkop** [comment] 2023-02-22 03:00
The first version of this comment sounded more defensive than I intended. Sorry about that; let me delete it and try again.

Sorry @tasogare3710 I have trouble understanding your last few comments.

This was the original problem statement: 
> ResourceBundle fails to load if the ResourceBundle is specified using the resourceBundle element of the CommandLine.Command annotation.

I believe I provided a solution: 
add `opens pn` in the `module-info` of the module that contains the resource bundle, and picocli will be able to successfully read ResourceBundles that are specified in the `resourceBundle` element of the `@CommandLine.Command` annotation.
My previous [comment](https://github.com/remkop/picocli/issues/1420#issuecomment-1437773509) goes in some detail on tests that prove this solution works.

After that, I did not understand your replies.  😅 
(I understand the words, but it is not clear to me what you want...)

Can you clarify if the proposed solution meets your requirements, or if there are further requirements?

**Comment by remkop** [comment] 2023-02-24 09:20
I updated the user manual:
added this section: https://picocli.info/#_resource_bundles_in_jpms_modules
I believe this resolves the issue, please let me know if this does not work for you.

**Closed by remkop** 2023-02-24 09:20 UTC
Labels: type: doc :blue_book:, status: help-wanted, theme: module
