### ISSUE TITLE
Nested ArgGroups do not enforce mutual dependency

### ISSUE THREAD

**Issue by rain-on** [remkop/picocli#938] opened 2020-02-06 05:57 UTC
I'm trying to do configure mutual-dependency across nested arg-groups, but either I'm not configuring it quite right, it can't be done, or its not implemented 🤷‍♂ .

Below is a file with a sample command line, and _my_ expected outputs to good/bad input.

```
package the.picocli.example;

import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Option;
import picocli.CommandLine.ParseResult;

public class SampleCmdLine {

  static class OtherOptions {
    @Option(
        names = "--other-option-1",
        arity = "1",
        required = true)
    private String firstOption;

    @Option(
        names = "--other-option-2",
        arity = "1",
        required = true)
    private String secondOption;
  }

  static class MySwitchableOptions {
    @Option(
        names = "--enable-more-options",
        arity = "0",
        required = true)
    private boolean tlsEnabled = false;

    @ArgGroup(exclusive = false)
    private OtherOptions options;
  }

  static class FullCommandLine {
    @ArgGroup(exclusive = false)
    private MySwitchableOptions switchableOptions;
  }

  public static void main(String[] args) {
    final CommandLine commandLine = new CommandLine(new FullCommandLine());
    ParseResult result;

    // Ideally this would FAIL (as the --enable-more-options is not set
    result = commandLine.parseArgs("--other-option-1=firstString", "--other-option-2=secondString");

    // Ideally this would PASS (and the switchableOptions would be null)
    result = commandLine.parseArgs("--enable-more-options");

    // Should fail as other-option-2 is not set (and defined as required)
    result = commandLine.parseArgs("--enable-more-options", "--other-option-1=firstString");
  }
}
```

**Comment by remkop** [comment] 2020-02-06 06:25
Thank you for raising this!

I was able to reproduce the issue (thanks for the clear example).
I believe that your expectation is correct that the first example should fail because `--enable-more-options` is missing.

I am investigating...

**Comment by remkop** [comment] 2020-02-06 07:53
I found the cause.

The `CommandLine.ParseResult.GroupMatch.validate()` method method oversimplifies things when validating the combination of options and subgroups. It simply counts the required args plus required subgroups, and compares that count with the number of present args and present subgroups, and based on that decides whether an element is missing.

This is an oversimplification, since if a required element is missing, and an optional subgroup is present, that should not cancel each other out.

I will fix this soon, and the fix will be included in the upcoming 4.2 release.

**Comment by rain-on** [comment] 2020-02-06 08:37
👍 Terrifyingly fast analysis :)

**Comment by remkop** [comment] 2020-02-06 09:41
:innocent: Thank you! Please drop picocli a GitHub :stars: star if you like the project.   :wink:

**Comment by rain-on** [comment] 2020-02-06 10:32
done ;)

**Comment by remkop** [comment] 2020-02-06 16:26
The fix has been committed to master.
Thank you again for reporting this!

If you want to verify, and play with the [latest features](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#-picocli-420-unreleased), do this:

```
git clone https://github.com/remkop/picocli.git
cd picocli
gradlew publishToMavenLocal
```

That should publish `picocli-4.2.0-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.0-SNAPSHOT` dependency.

**Closed** 2020-02-06 16:26 UTC
Labels: arg-group, bug

**Comment by remkop** [comment] 2020-02-12 02:44
@rain-on, All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including this fix. Enjoy!
