### ISSUE TITLE
Parse Multiple Commands and their options from one line

### ISSUE THREAD

**Issue by bmaxwell** [remkop/picocli#319] opened 2018-04-01 18:38 UTC
In issue #127 , it looked like picocli could parse out multiple commands, but I am having issues.

It looks like it parses the top level Command and then 1 sub command, then it warns the 2nd command is unmatched, it appears it is looking at the 1st subcommand instead of the top level command to match.  Is there something missing in the setup or is this currently not possible?

[picocli WARN] Unmatched arguments: [def, -d, dvalue]
picocli.CommandLine command: Config
picocli.CommandLine command: abc

Since there are no positional parameters, I was trying to get Config, abc, def all parsed.

	@Command(name="Config", subcommands={ABC.class, DEF.class})
	public static class Config {
		@Option(names={"-c"})
		private String c;	
		public String getC() {
			return c;
		}
	}	
	@Command(name="abc", subcommands={})
	public static class ABC {
		@Option(names={"-a"})
		private String a;		
		public String getA() {
			return a;
		}
	}	
	@Command(name="def", subcommands={})
	public static class DEF {
		@Option(names={"-d"})
		private String d;		
		public String getD() {
			return d;
		}
	}
	public static void main(String[] args) {
		String[] testArgs = {"-c", "cvalue", "abc", "-a", "avalue", "def", "-d", "dvalue" };
		Config cfg = new Config();
		CommandLine commandLine = new CommandLine(cfg);
		commandLine.setUnmatchedArgumentsAllowed(true);
		List<CommandLine> recognized = commandLine.parse(testArgs);
		for(CommandLine cl : recognized) {			
			System.out.printf("%s command: %s\n", cl.getClass().getName(), cl.getCommandName());
		}
	}

**Comment by remkop** [comment] 2018-04-01 22:58
The issue you mentioned (#127) resulted in the current picocli behaviour: picocli expects the command line to contain a hierarchy of subcommands. So if it sees a command line like this:

```
config abc def
```
... picocli expects `def` to be a subcommand of `abc`. 

I believe this is the convention used by most other command line apps. 

That said, I would not oppose an `accepSiblingSubcommands` parser mode being added. Are you interested in contributing a pull request for this?

**Comment by remkop** [comment] 2019-03-04 23:39
Hi @bmaxwell  and @kaibioinfo, the plan is that picocli 4.0 will add support for composite repeating groups.

The goal is that argument groups will support:
* mutually exclusive options (#199)
* option that must co-occur (#295)
* option grouping in the usage help message (#450)
* repeating composite arguments (#358) (this makes more sense to me than the repeatable subcommands proposed here and in #454 and #434)

This is currently work in progress, and an early (but insufficient - lacking support for repeating composite arguments) version is currently in master. The #199 ticket has some comments that describe the current state of things and follow-up plans.

**Comment by remkop** [comment] 2019-06-13 15:19
Closing this ticket as a duplicate of  #454. 
 #454 has more discussion of the use case.

**Closed by remkop** 2019-06-13 15:19 UTC
Labels: duplicate
