### ISSUE TITLE
option-parameter gets lost in Argument Groups

### ISSUE THREAD

**Issue by waacc-gh** [remkop/picocli#1054] opened 2020-05-18 22:14 UTC
see: #1055

```
    @ArgGroup(exclusive = false, multiplicity = "1..*")
    private List<Modification> modifications = null;

    private static class Modification {
        @Option(names = { "-f", "--find" }, required = true)
        public  Pattern findPattern = null;
        @ArgGroup(exclusive = true, multiplicity = "1")
        private Change  change      = null;
    }

    private static class Change {
        @Option(names = { "-d", "--delete" }, required = true)
        public boolean delete      = false;
        @Option(names = { "-w", "--replace-with" }, required = true)
        public String  replacement = null;
    }
```
called with:
- `-f pattern -d` --> accepted --> ok
- `-f pattern -w text` --> accepted --> ok
- `-f pattern -d -w text` --> error --> ok
- `-d -f pattern -w text` --> error --> ok
- `-f pattern1 -f pattern2 -d` --> accepted --> wrong: `findPattern = "pattern2"`, `"pattern1"` is lost/ignored

**Comment by remkop** [comment] 2020-05-18 22:47
@waacc-gh Thank you for raising this!
I have been able to reproduce the issue.
Still investigating the cause...

**Comment by remkop** [comment] 2020-05-25 02:08
Thank you for raising this.
I believe this is fixed in master now. 

To verify, check out picocli master locally, and build it with `publishToMavenLocal`. That should publish `picocli-4.3.3-SNAPSHOT` to your local .m2 Maven cache.

```
git clone https://github.com/remkop/picocli.git
cd picocli
gradlew publishToMavenLocal
```

You can then try this in a project that uses the `info.picocli:picocli:4.3.3-SNAPSHOT` dependency. Feedback very welcome!

**Closed by remkop** 2020-05-25 02:08 UTC
Labels: arg-group, bug
