### ISSUE TITLE
How to control usage text width 

### ISSUE THREAD

**Issue by pditommaso** [remkop/picocli#276] opened 2018-02-02 12:36 UTC
Is it possible to control the width of the printed usage width. I've noticed that by default it doesn't usa all available screen size.

**Comment by remkop** [comment] 2018-02-02 13:01
This is on the roadmap (#159) but not supported yet.

I just added some notes to that ticket with some thoughts on what functionality to provide and what the API for these could look like. Please take a look and let me know your thoughts. If you feel like providing a pull request, that would be great!

**Comment by pditommaso** [comment] 2018-02-02 13:04
Sure thing, I'll do. Thanks. 

(I've have a few other questions, is GitHub the proper place to place them?)

**Comment by remkop** [comment] 2018-02-02 13:18
Oops, I saw your comment on #159 first and asked the same question twice. Sorry.  :-)
GitHub is fine for any questions/bug reports/feature requests. Go for it!

**Comment by remkop** [comment] 2018-02-05 09:49
Do you mind if we close this ticket as a duplicate of #159?

**Comment by pditommaso** [comment] 2018-02-05 09:52
No problem!

**Closed** 2018-02-05 09:52 UTC
Labels: duplicate
