### ISSUE TITLE
UnsupportedCharsetException: cp65001 with vs code

### ISSUE THREAD

**Issue by epuni** [remkop/picocli#1474] opened 2021-11-20 17:16 UTC
I was trying out this library in an empty java + maven project in vs code on windows 10, upon running any simple application i get this:
```
Exception in thread "main" java.nio.charset.UnsupportedCharsetException: cp65001
        at java.base/java.nio.charset.Charset.forName(Charset.java:526)
        at picocli.CommandLine.getStderrEncoding(CommandLine.java:14531)
        at picocli.CommandLine.getErr(CommandLine.java:1236)
        at picocli.CommandLine.handleUnhandled(CommandLine.java:2097)
        at picocli.CommandLine.execute(CommandLine.java:2083)
        at com.example.App.main(App.java:24)
```

The command line of the vs code java extension when launching as debug is the following:
```
cmd /C "C:\Users\<username>\.vscode\extensions\vscjava.vscode-java-debug-0.36.0\scripts\launcher.bat "C:\Program Files\OpenJDK\bin\java.exe" -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:54512 -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8 @C:\Users\<username>\AppData\Local\Temp\<random name>.argfile com.example.App <actual application arugments>"
```

The cause seems to be the default launcher.bat which does:
```
REM Change code page to UTF-8 for better compatibility.
@chcp.com 65001 > NUL 
```

The only other reference to this problem is in #1457 but it's related to argument files while it's not the case here (at least i think, the argfile here seems to be used only for vm args). 
The fix proposed in that PR doesn't work as the command line already includes `-Dfile.encoding=UTF-8`.

I tried adding several options such as `-Dsun.stdout.encoding=UTF8 -Dsun.err.encoding=UTF8` to the vmargs and none worked, ultimately the the only workaround to get it working for me was changing code page to 850 (cmd's default one) in launcher.bat which is not desirable as it will be overwritten when the extension updates and i don't know if it may break other projects.

Is there anything i'm missing ? Guess even if it's not a problem on your end it's worth noting it in the docs.

**Comment by epuni** [comment] 2021-11-20 17:17
Minimal way to reproduce this without vs code:
Build anything with picocli, then in a cmd run the follwing
```
chcp 65001
java -jar demo.jar
REM Won't work either:
java -DFile.encoding=UTF8 -jar demo.jar
```

**Comment by remkop** [comment] 2021-11-21 00:53
@epuni Thank you for raising this!
Are you also seeing this error with the previous version: picocli 4.6.1?

It is likely that this is caused by a recent change in the 4.6.2 release (https://github.com/remkop/picocli/releases/tag/v4.6.2).

**Comment by epuni** [comment] 2021-11-21 10:28
Just tested 4.6.1 and it works as expected.

**Comment by remkop** [comment] 2021-11-21 11:17
Thank you for the confirmation.
This looks like a regression introduced by #1320 #1321.
I will add some code to set `UTF-8` instead when the String `cp65001` is specified.

**Comment by remkop** [comment] 2021-11-21 11:18
Does anyone have any idea how to add a unit test for this? :-)

**Comment by remkop** [comment] 2021-11-21 11:20
I pushed a fix that should address this issue. Thank you again for raising this!

(Ideas for unit testing this still welcome. 😅 )

**Closed** 2021-11-21 11:19 UTC
Labels: bug, shell

**Comment by Druckles** [comment] 2022-08-10 16:46
I've just had the same problem in Cygwin with cp20127:

```
Exception in thread "main" java.nio.charset.UnsupportedCharsetException: cp20127

        at java.base/java.nio.charset.Charset.forName(Charset.java:528)
        at picocli.CommandLine.getStderrEncoding(CommandLine.java:14531)
        at picocli.CommandLine.getErr(CommandLine.java:1236)
        at picocli.CommandLine.handleUnhandled(CommandLine.java:2097)
        at picocli.CommandLine.execute(CommandLine.java:2093)
  ...
```

Downgrading to 4.6.1 fixed the problem.

**Comment by remkop** [comment] 2022-08-11 00:32
@Druckles Thank you for raising this!
would you mind raising a separate ticket for this?

**Comment by remkop** [comment] 2023-05-25 02:13
> I've just had the same problem in Cygwin with cp20127:
> 
> ```
> Exception in thread "main" java.nio.charset.UnsupportedCharsetException: cp20127
> 
>         at java.base/java.nio.charset.Charset.forName(Charset.java:528)
>         at picocli.CommandLine.getStderrEncoding(CommandLine.java:14531)
>         at picocli.CommandLine.getErr(CommandLine.java:1236)
>         at picocli.CommandLine.handleUnhandled(CommandLine.java:2097)
>         at picocli.CommandLine.execute(CommandLine.java:2093)
>   ...
> ```
> 
> Downgrading to 4.6.1 fixed the problem.

It is unclear whether this is a Cygwin issue, or what else is going on... (potentially related: https://github.com/rubygems/rubygems/issues/4871, which mentions "Platforms   ruby, x64-mingw32": also cygwin)

Unclear how to remediate this in picocli (if we wanted to): what Java encoding should be used when system property `sun.stderr.encoding` has value `cp20127`?

(And for bookkeeping purposes, if further action is required, we need to create a new ticket.)
