### ISSUE TITLE
Picocli 4.6.3 : autocompletion of directory names not working anymore

### ISSUE THREAD

**Issue by philgdn** [remkop/picocli#1644] opened 2022-03-31 12:35 UTC
I'm facing a regression with Picocli 4.6.3 : the autocompletion of filenames doesn't work anymore.

The help of my `OdsManager` app:

`OdsManager extractLoadOds [-hV] [-p PROPERTIES] [JOBFILE [--maxErrorsByExtraction MAX_ERRORS] [--[no-]cleanBeforeExtract] [-f | -s SINCE]] [[--commitAfter <commitLoadAfter>] `

When I enter `OdsManager extractLoadOds ` on the command line, with Picocli 4.6.2 hitting the TAB twice I was getting the possibility to autocomplete **directory names** for the JOBFILE parameter:

- if  I hit TAB twice I get the list of files and directories in the current directory 
- if I then type `jo` TAB TAB (for the existing `jobs/` directory)... I get no suggestions

This was working in 4.6.2 but doesn't work anymore in 4.6.3.

**Comment by remkop** [comment] 2022-04-01 09:31
Thank you for raising this!
I will take a look.

**Comment by remkop** [comment] 2022-06-06 04:40
I finally had some time to look at this.
This seems to be caused by this change: https://github.com/remkop/picocli/pull/1473: if I comment out the `local IFS=$'\n'` in the completion script section for the positional parameter, completion seems to work for partial directory names.

I need to spend more time debugging this.

**Comment by NewbieOrange** [comment] 2022-09-01 16:24
Is this reproducible with https://raw.githubusercontent.com/remkop/picocli/master/src/test/resources/picocompletion-demo_completion.bash?

**Comment by philgdn** [comment] 2022-10-20 09:05
Sorry I missed your message of September 1.

With the provided `picocompletion-demo_completion.bash` script I get the completion for the directory names

**Comment by NewbieOrange** [comment] 2022-10-20 09:13
Can you provide a minimal example to reproduce the issue?

**Comment by philgdn** [comment] 2022-10-21 14:18
Here are examples (_not so minimal sorry_) : [Examples.zip](https://github.com/remkop/picocli/files/9839753/Examples.zip)

- `SolifeOdsBatchManager_completion_462` was  generated by Picocli 4.6.2 and works as expected
- `SolifeOdsBatchManager_completion_463` was  generated by Picocli 4.6.3 : autocompletion don't work for _directories_

To reproduce the problem (with SolifeOdsBatchManager_completion_463) in a directory containing files and directories type (for example a directory `dir1` :

`SolifeOdsBatchManager extractLoadOds d` then TAB.

The autocompletion should complete the `dir1` directory... but it doesn't

**Comment by remkop** [comment] 2022-10-23 00:16
Hi @NewbieOrange, great to hear from you!
I would like to include a fix for this issue (#1644) in the picocli 4.7 release; this ticket has been on my radar but I never got time to look at it... 😓 

I believe this PR is related: https://github.com/remkop/picocli/pull/1759 because it also looks at setting `local IFS=$'\n'` in the completion script.

**Comment by NewbieOrange** [comment] 2022-10-23 04:10
@remkop after some debugging, the issue seems to be caused by `COMPREPLY` has been set with wrong IFS; and this should be fixed by #1759.

**Comment by remkop** [comment] 2022-10-23 04:12
Oh awesome! 🤩 
So, #1759 will also fix #1644?
Thank you for looking into this!

**Comment by philgdn** [comment] 2022-10-24 09:49
> @remkop after some debugging, the issue seems to be caused by `COMPREPLY` has been set with wrong IFS; and this should be fixed by #1759.
> 
> edit: @philgdn maybe you can test with #1759?

@NewbieOrange , here is the completion generated with the #1759 : [SolifeOdsBatchManager_completion_1759.zip](https://github.com/remkop/picocli/files/9850630/SolifeOdsBatchManager_completion_1759.zip)

Unfortunately, it doesn't work : no completion yet for directory names

**Comment by NewbieOrange** [comment] 2022-10-27 13:07
> > @remkop after some debugging, the issue seems to be caused by `COMPREPLY` has been set with wrong IFS; and this should be fixed by #1759.
> > edit: @philgdn maybe you can test with #1759?
> 
> @NewbieOrange , here is the completion generated with the #1759 : [SolifeOdsBatchManager_completion_1759.zip](https://github.com/remkop/picocli/files/9850630/SolifeOdsBatchManager_completion_1759.zip)
> 
> Unfortunately it doen't work yet with directory names !

Looks #1759 introduced another issue... Please try #1863

**Comment by philgdn** [comment] 2022-10-27 15:02
@NewbieOrange , here is the completion generated with the #1863 : [SolifeOdsBatchManager_completion_1863.zip](https://github.com/remkop/picocli/files/9880549/SolifeOdsBatchManager_completion_1863.zip)

The completion of directory names works now !

**BUT** it is now the commands that doesn't work anymore.

- if I type `SolifeOdsBatchManager extract` then `TAB` (to get _extractOds_ or _extractLoadOds_) no completion is suggested
- if I type `SolifeOdsBatchManager ` then `TAB` the list of all commands is printed on the line

**Comment by NewbieOrange** [comment] 2022-10-29 11:34
@philgdn can you try with #1863 again?

**Comment by philgdn** [comment] 2022-10-29 13:10
> @philgdn can you try with #1863 again?

@NewbieOrange , it's OK now : completion of commands AND directory names are working!

Thanks four your help!

**Comment by NewbieOrange** [comment] 2022-10-30 04:36
@remkop fixed by #1863

**Comment by NewbieOrange** [comment] 2022-10-31 13:33
Hi, @philgdn can you please retest with #1863? To fix the tests I made some changes ❤️

**Comment by philgdn** [comment] 2022-10-31 14:15
@NewbieOrange , it's still OK: completion of commands AND directory names are working!

**Closed** 2022-10-31 16:37 UTC
Labels: type: bug :bug:, theme: auto-completion
