### ISSUE TITLE
behavior of defaultValue

### ISSUE THREAD

**Issue by sjyMystery** [remkop/picocli#962] opened 2020-02-20 03:07 UTC
Hi, guys:
  There's an unexpected behavior of the `defaultValue` param in `@Option` Annotation.
   When use default values from environment variables of invalid types, it always throws ParameterException even though I passed the value of the argument.

# How to solve it
  Maybe we can disable the type-checking of default value when the argument value has been already passed.

  And I will be honored to submit the example code of this situation and create a  pull request if necessary.

**Comment by remkop** [comment] 2020-02-20 03:51
Can you please show how to reproduce this problem?

**Comment by sjyMystery** [comment] 2020-02-20 08:05
Of course, the code is below:

```java
import picocli.CommandLine;

@CommandLine.Command(name = "run")
public class App implements Runnable {

    @CommandLine.Option(names = "--port", defaultValue = "${env:PORT}", required = true)
    Integer PORT;


    static public void main(String[] args) {
        App app = new App();
        args = new String[]{"--port", "5672"};
        CommandLine cmd = new CommandLine(app);
        cmd.execute(args);
    }

    public void run() {
        System.out.println(PORT);

    }
}
```

before run :
```shell script
export PORT="xxx"
```

**Comment by sjyMystery** [comment] 2020-02-20 08:05
then may got:

```
Invalid value for option '--port': 'xxx' is not an int
Usage: run [--port=PORT>]
      --port=<PORT>
```

**Comment by remkop** [comment] 2020-02-20 09:26
@sjyMystery Thank you for the clarification. I understand the issue now.
It looks like this is the same cause as this ticket: https://github.com/remkop/picocli/issues/961 (I just changed the title of that ticket.)

Please read my [comment on that ticket](https://github.com/remkop/picocli/issues/961#issuecomment-588217786) for more details.

Are you interested in providing a pull request for this? That would be great!

**Comment by sjyMystery** [comment] 2020-02-21 11:18
I've get your point.By the way, is there anything need or suggested to read before I make a pr?Thanks.

**Comment by remkop** [comment] 2020-02-21 11:31
@sjyMystery There is no documentation on the implementation, just the source code. :-)

It may be as simple as reordering these 2 lines in `CommandLine$Interpreter.parse(List, Stack, String[], List)` on [line 11486](https://github.com/remkop/picocli/blob/master/src/main/java/picocli/CommandLine.java#L11486):

Before: 

```java
private void parse(List<CommandLine> parsedCommands, Stack<String> argumentStack, String[] originalArgs, List<Object> nowProcessing) {
...
  try {
    applyDefaultValues(required); // currently defaults are applied first
    processArguments(parsedCommands, argumentStack, required, initialized, originalArgs, nowProcessing);
  } catch (InitializationException ex) {
...
```

After: 

```java
private void parse(List<CommandLine> parsedCommands, Stack<String> argumentStack, String[] originalArgs, List<Object> nowProcessing) {
...
  try {
    processArguments(parsedCommands, argumentStack, required, initialized, originalArgs, nowProcessing);
    applyDefaultValues(required, initialized);  // only apply defaults to the missing args
  } catch (InitializationException ex) {
...
```

Then, in `applyDefaultValues()`, we only modify the `ArgSpec` objects that are not in the `initialized` set.

But let's add some tests to verify.

**Comment by remkop** [comment] 2020-03-07 22:05
@sjyMystery Have you had a chance to look at this? Let me know if you get stuck anywhere, I will try to help. :-)

**Comment by remkop** [comment] 2020-04-19 22:01
Fixed in master.

To verify this, check out picocli master locally, and build it with `publishToMavenLocal`. That should publish `picocli-4.2.1-SNAPSHOT` to your local .m2 Maven cache.

```
git clone https://github.com/remkop/picocli.git
cd picocli
gradlew publishToMavenLocal
```

You can then try this in a project that uses the `info.picocli:picocli:4.2.1-SNAPSHOT` dependency. Feedback very welcome!

**Closed by remkop** 2020-04-19 22:01 UTC
Labels: enhancement, in-progress
